### PR TITLE
changed screenshot (fixes #2975)

### LINKED ISSUE #2975: Unclear screenshot in Actions on List Page
**Problem:**
Unclear screenshot in Actions on List Page .

**Steps to reproduce the problem:**
Going to [Courses, under Planet Manual](https://open-learning-exchange.github.io/#!./pages/manual/planet/./course.md)

**Screenshots:**

sourting courses screenshot it confusing 1

**proposed solution:**

Update screenshot, removing the pop up box to the right.

### PR DESCRIPTION
**Pull request by chtelmko**
Fixes # 2975

Description
Redo pull request of pull request #2981 and pull request #2976. To make my commit  _verified_.

Changed screen shot for better clarity.

Raw.Githack preview link
https://raw.githack.com/chtelmko/chtelmko.github.io/changepic/#!pages/manual/planet/course.md

### CODE REVIEW

**Comment by LordJashin32** [comment]
I don't really get the point of the new vs old screen shot. To me it seems like it would be more useful to just circle in red the "+" button. But i guess the screen we can see better without the menu in the way?

**Comment by LordJashin32** [comment]
Also you need to make sure to delete your old PR's when you make the same one over again. Cheers.

**Comment by chtelmko** [comment]
Will delete the old requests in the future. Was not sure the policy for it. Yes, that's what I was thinking the screen was in the way of the rating button. And the opened up screen didn't relate to that step

**Comment by chtelmko** [comment]
Thank you, for deleting my pull requests!

**Comment by chtelmko** [comment]
Oh I see, what you mean. I thought that screenshot was trying to show how to sort courses, not add them.

**Comment by chtelmko** [comment]
should i combine this pull request with this one #2987? that way it will be clearer what I am changing.

**Comment by chtelmko** [comment]
Would it be better to combine this with pull request #2987?

**Pull request closed without merging**
