### PR TITLE
Create avin-sharma.md

### PR DESCRIPTION
**Pull request by avin-sharma**
### Description
Created avin-sharma.md

Contains the following information:
- My name, location/time zone, and OS.
- A short description of me.

Uses the following Markdown elements:
1. Headings
2. Text Attributes
3. Horizontal Rule
4. Links
5. Lists

### Raw.Githack preview link

https://raw.githack.com/avin-sharma/avin-sharma.github.io/add-avin-sharma-profile/#!pages/vi/profiles/avin-sharma.md

### CODE REVIEW

**Comment by gautamsethi1** [comment]
> @avin-sharma Your Githack link does not work - it should show a page instead of the raw source code. Please review the sample githack link at https://open-learning-exchange.github.io/#!pages/vi/vi-github-and-markdown.md.

To add on to this point, you forgot the #! before pages. Everything else looks good in your link.

**Comment by avin-sharma** [comment]
@anthonyhvo12 @gautamsethi1 Fixed the Githack link, it now shows the page instead of the raw source code.

**Comment by anthonyhvo12** [comment]
@avin-sharma There appears to be an extra cell to the right of your table. You might also want to fix the mistyped "graduate" in the "About Me" part. The rest looks good to me. 
Screen Shot 2020-06-02 at 9 11 54 PM

**Comment by avin-sharma** [comment]
@anthonyhvo12  Fixed the table and typo. Thanks for the review.

**Pull request merged**
