### PR TITLE
Sgardas

### PR DESCRIPTION
**Pull request by sgardas**
Fixes #

### Description
updated sgardas.md

### RawGit preview link
https://raw.githubusercontent.com/sgardas/sgardas.open-learning-exchange.github.io/sgardas/pages/vi/profiles/sgardas.md

### CODE REVIEW

**Comment by sgardas** [comment]
sgardas

**Comment by xyb994** [comment]
@sgardas 
- It looks like you forgot to add .md extension to the file name
- Please ensure the pull request meet 3 check items specified at  https://open-learning-exchange.github.io/#!pages/vi/vi-github-and-markdown.md#Open_a_pull_request

**Comment by xyb994** [comment]
@sgardas 
- looks like you misunderstood what [rawgit](https://rawgit.com) link is, please look back step 3 for the correct format
- please rename your forked repo to `sgardas.github.io` so GitHub knows it's a GitHub Pages site.

**Comment by Going-Gone** [comment]
rawgit = 
https://**rawgit.com**/sgardas/sgardas.open-learning-exchange.github.io/sgardas/**#!pages**/vi/profiles/sgardas.md

**Comment by xyb994** [comment]
@sgardas Are you still working on this?

**Comment by sgardas** [comment]
I am out of station now and will be updating everything by this weekend.

**Comment by sgardas** [comment]
@xyb994  I have renamed my fork repo to sgardas.github.io and my rawgit is https://rawgit.com/sgardas/sgardas.open-learning-exchange.github.io/sgardas/#!pages/vi/profiles/sgardas.md

**Comment by Going-Gone** [comment]
Thank you for the update.

**Pull request merged**
