### PR TITLE
Offline mdwiki site

### PR DESCRIPTION
**Pull request by paulbert**
Use a different mdwiki html file with all assets inline to use offline.  Works by opening the index.html file in the browser with file:/// in most browsers (see the [mdwiki faq](http://dynalon.github.io/mdwiki/#!faq.md) for browser support)

It's the first step to issue https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/458 and the next is to add it as a BeLL-Apps resource.

There are a few small differences offline and online that I've noted so far:
1. The font is different, as the current theme uses the Lato webfont from Google
2. The logo is missing offline

As a note, this mdwiki html file has been slightly modified to include the bootstrap flatly theme rather than the default theme in the html.  Otherwise the CSS wouldn't work.  I forked the mdwiki repo [here](https://github.com/paulbert/mdwiki/tree/0.6.x) with that change on the 0.6.x branch so we have that to work off of.

### CODE REVIEW

**Comment by paulbert** [comment]
I didn't notice the "for developers" portion on the bottom of the wiki before, but now updated the index.html to include the external link and title functionalities directly in the mdwiki build

**Comment by waryhermit** [comment]
@paulbert Have any ideas on how to fix the icon? Could we just download the font?

**Comment by paulbert** [comment]
Apparently yes to both!  The font displays a little differently, but it is Lato now.

**Comment by dogi** [comment]
awesome @paulbert - since this are very big changes - we need to test more ;)
promise that Satur after 1600 I will dig in :D

**Comment by waryhermit** [comment]
@paulbert Looks pretty good. I was wondering if you can think of any downsides to including the external js/css files directly in the HTML. Do those resources change often? Will it effect the bandwidth/loading speed etc, of the existing MDWiki?

**Comment by paulbert** [comment]
@mappuji I made a few changes to the mdwiki code found on [this fork](https://github.com/paulbert/mdwiki/tree/0.6.x) to get the wiki working offline.  These changes add the bootstrap theme as inline CSS and the Lato font used is included in the `/fonts` folder.  That allows the wiki to function even when disconnected from the internet by opening index.html from the file system using one of the supported browsers as documented in the [mdwiki faq](http://dynalon.github.io/mdwiki/#!faq.md).  You can test it by trying it out offline.

@dogi Makes sense, I wasn't thinking this would happen quickly!

@waryhermit The CDN links were already for specific versions of the libraries, so those resources were staying the same anyway.  In doing a little research I'm seeing the main pro of having scripts & styles is that it's a little faster in terms of loading the assets (fewer network calls), but a little slower in terms of processing because the browser will cache those external files ([see pros and cons for CSS here](https://varvy.com/pagespeed/inline-small-css.html)) and [some more for JS here](http://knowledgehills.com/javascript/external-javascript-syntax-disadvantages.htm).  I haven't seen a noticeable difference in either version.  I'm seeing it take roughly half a second to load the wiki for both versions.  The other main con that's often cited is that it's harder to maintain one big CSS tag or js script, but that's not a pertinent issue here since there is a build system in place.

**Comment by dogi** [comment]
https://rawgit.com/paulbert/paulbert.github.io/offline/#!index.md

**Comment by sarvanivadali** [comment]
screen shot 2017-03-17 at 4 41 25 pm
Looks like this to me when I tried it online,except for the logo.

**Comment by waryhermit** [comment]
@sarvanivadali Did you mean offline or online?

**Comment by sarvanivadali** [comment]
Sorry ,it was offline.

**Comment by mappuji** [comment]
@dogi for HTML app or offline wiki I propose to redefine it.

- What is actually htmlapp? I propose, HTML app is a static HTML app (with HTML, CSS, and js). It works with no database but certainly, need a static HTTP server. Coz, the problem is basically separating assets (CSS, js) from HTML is inevitable, but since we are using static HTTP server it is okay to have an HTML app which can't run directly by open it in browser with ```file:///``` (we need an HTML app open by ```http://``` instead. And it is also applicable for TurtleBlock and HelloNurse which I and other interns upload it to BeLL Nation - we can't open it by directly open it in the browser).

- Because it is for BeLL-App and we need to have a completely offline HTML app? I think, since the BeLL-App run on a server or at least mini server with couch, my definition of HTML app is compatible with this.

- For @paulbert solution, I think to make all the CSS or js files inline in HTML is not a beautiful solution. Let the mdwiki as we have now and we still put it on BeLL-App nation I believe.

**Comment by i5o** [comment]
Hi everyone, it's been a while since I used couchdb and stuff to generate turtle js as a bell resource (turtlejs waaay back in the past)

I don't recommend including the css or javascript directly into the index.html (but probably something like /css/bootstrap.css instead of calling the bootstrap CDN), I don't know if it's still possible but with turtlejs I managed to keep the structure.
The main problem seems to be the .md files which needs to be "rendered".
I don't know if these are generated by github (using jekyll) or it's client side.
If it's client side I recommend converting them to HTML and then add the "index.html" as a resource or so; I guess I need to re-study the couchdb app thing again :)

**Comment by mappuji** [comment]
> I don't recommend including the css or javascript directly into the index.html (but probably something like /css/bootstrap.css instead of calling the bootstrap CDN),

Good point, I strongly agree with this.

**Comment by waryhermit** [comment]
@i5o I believe the end goal is for the same version of the MDWiki to be online and in the BeLLApps, so each time we can push the changes to the BellApp with no manual work. The markdown normally seems to render fine offline so it would be client side. This pull request is very close to working as is.

@mappuji I don't understand the leap from preferring not to inline assets to requiring a server. If tutleblocksJS can be run directly from index.html why can't the MDwiki?

Since you both don't like the inline assets could you explain more? Its not something @paulbert came up with, but from the official MDWiki people as far as I understand.

**Comment by i5o** [comment]
Basically including the content inline, would decrease the readability
of the code itself.
Also, when getting new versions of code (ie bootstrap): instead of
changing the whole content of  index.html you could just change the
content of the css.

Also turtleblocks does loads the assets from /css/
https://github.com/walterbender/turtleblocksjs/blob/master/index.html#L8

**Comment by mappuji** [comment]
Basically, I've very impressed with this PR since @paulbert tried to make the MDWiki run directly from ```file://``` , but I want to emphasis on a fundamental thing from my previous experience with porting HTML resources. My point is, as long as the HTML resource is served with a static HTTP server, we don't need to make all assets inline.

**Comment by waryhermit** [comment]
@i5o Exactly my point - using external files does *not* require a server, as evidenced by turtle blocks. Do we often work on the inline code? If not, it doesn't matter as much if it is readable. It is my understanding that this inline stuff is rarely changed, e.g when we upgrade the wiki. I agree that for code we are developing it makes sense to have it as readable as possible and then only inline/minify/etc with tools afterward.

@mappuji We can make the assets inline or not regardless of how its hosted is what I am trying to say.


Anyway, I don't care which way we include the files, so long as it works from the bell app and from github without any internet and using the same files for both. If we can achieve that the rest are just minor annoyances as far as I am concerned.

**Comment by waryhermit** [comment]
As @paulbert originally said he based his stuff off the version of MDwiki that was intended for offline use, which comes with the files in lined, see http://dynalon.github.io/mdwiki/#!download.md

**Comment by mappuji** [comment]
Interesting. @waryhermit I will do deep research about it ;)
Thanks.

**Comment by waryhermit** [comment]
@dogi @i5o @mappuji

So I am unsure right now, is this pull request in limbo because of some kind of error or issue? Or are we just not sure if we prefer to use inline files vs external files?

**Comment by paulbert** [comment]
Hi @dogi @i5o @mappuji @waryhermit 
Lots of comments on this while I was away!

So a big part of this is that I don't think we should be updating index.html directly.  The mdwiki javascript is inline and uglified as a part of it (and is inline in all versions), so updating that is already quite difficult.  And, as I found out, there were a lot of small changes to that file that weren't documented and could have been lost as I created a new build from the mdwiki assets for this and adding support for a 404 page.  Using a fork of the mdwiki repo gives us a place to document custom code we've written for our use as well as working with non-uglified code (and learning to build it means you can also build a debug version to work with in the browser).

That being said, inlining the js & css libraries does mean that when we want to update Bootstrap or jQuery we'd have to rebuild the index.html (a small, but still extra step) rather than simply replacing the file.  That should be a pretty rare occurrence, and I'd say it's likely if we're updating those files we'd be changing quite a bit more (i.e. moving on to a newer release of mdwiki or migrating to another solution).  If the group would rather not inline them, though, I can try to update this to use external scripts and styles that will also work offline.

As a note, as a looked into this solution it does seem that currently the developer of mdwiki is (slowly - last commit 9 months ago) working on a 0.7 release.  I don't think there will be any updates to the base mdwiki code coming any time soon.

**Comment by waryhermit** [comment]
@paulbert Thank you for clarifying your process. As I understand what you said, you edited the MDwiki in non-minified state and then built it? I think that might address the read-ability problem some had. I agree with you when about not needing to update often. Could you link to the MDwiki you made the changes in before being minified?

>I found out, there were a lot of small changes to that file that weren't documented

Changes made by us, or because our version was old?

Also, here are the errors I was talking about in chat:
```
[WARN] Could not get ./  index.html:236:13775
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.  index.html:143:40351
XML Parsing Error: not well-formed
Location: file:///C:/Users/waryh/Documents/GitHub/waryhermit.github.io/navigation.md
Line Number 2, Column 5:  navigation.md:2:5
XML Parsing Error: not well-formed
Location: file:///C:/Users/waryh/Documents/GitHub/waryhermit.github.io/config.json
Line Number 1, Column 1:  config.json:1:1
[ERROR] Theme  not found, removing link  index.html:236:13775
XML Parsing Error: not well-formed
Location: file:///C:/Users/waryh/Documents/GitHub/waryhermit.github.io/index.md
Line Number 1, Column 9:  index.md:1:9
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.
```

**Comment by paulbert** [comment]
Link for my custom mdwiki:
https://github.com/paulbert/mdwiki/tree/0.6.x

I worked off the 0.6.x branch since that more closely matches what we use and the master branch didn't seem to be stable/working.  We could fork this from the OLE account and force push this branch back into the master for ease of use and to allow others to manage it, too.

The changes were I'm 99% certain made by us.  They were for adding the logo, changing the font, and changing the favicon.  Little things that wouldn't break the page so eventually they'd probably get lost in the flow.

The errors:
* The ones starting with brackets are actually from mdwiki itself.  I'll have to look into those and can probably fix them.
* The getPreventDefault warning/error is from jQuery.  I can try switching to a newer version for that.
* I'm a bit stumped on the XML parsing error, but will see if I can figure out why that's coming up.  I didn't change any of the files referenced in those errors.

**Comment by paulbert** [comment]
Upgrading to the latest jQuery worked for the mdwiki errors and the getPreventDefault.

The XML parsing error is still puzzling.  The markdown and config files are loaded in with jQuery ajax requests.  For some reason I think when loading offline the browser thinks it's looking for XML format and throwing errors even though in the requests text is specified as the data type.  Despite this, the pages are loading fine.

When looking at this online, interestingly enough, there aren't any XML parsing errors.

https://rawgit.com/paulbert/paulbert.github.io/offline/#!index.md

**Comment by waryhermit** [comment]
@paulbert Seems like it might be a browser bug.. I only checked in firefox.

**Comment by paulbert** [comment]
To clarify from the gitter chat, at this stage this will only work in Firefox because it uses the filesystem (file:///) to run.  Chrome blocks AJAX calls in javascript entirely when served from the filesystem, but Firefox allows them.  This should be solved by converting to a CouchApp, but in the meantime we decided to merge this.

**Pull request merged**
