### PR TITLE
Localize the css and js assets

### PR DESCRIPTION
**Pull request by mappuji**
This is the new PR for [Generate htmlapp via couchapp #462](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/462#issuecomment-274483304) and to solve the issue #458 .

For test the PR you can check [the raw git here](http://rawgit.com/mappuji/mappuji.github.io/localize-vendor/#!index.md), don't forget to check in-browser javascript console to track any js errors (click CTRL+SHIFT+J for windows or mac equivalent).

@dogi @hikaruit15 and @waryhermit please review 😄

### CODE REVIEW

**Comment by hikaruit15** [comment]
It seems to be fine with your modifications, but there is still a problem. In `jquery.min.js` file, some code get `bootstrap.min.css` from external link. This makes our page has no good looking.
screen shot 2017-01-23 at 2 45 57 pm

**Comment by mappuji** [comment]
image

Have you check the changes with my PR modification, I have tested the changes using apache in my local computer and it works fine.

**Comment by dogi** [comment]
>  I have tested the changes using apache in my local computer and it works fine.

@mappuji using apache is against the rules ;)
in the moment you need apache to serve your htmlapp it is no htmlapp anymore ...

@hikaruit15 @waryhermit do I make sense?

**Comment by mappuji** [comment]
Thanks @dogi , but I use the apache because I want to emulate the http server. I think, the rawgit version prove that its work fine.

**Comment by hikaruit15** [comment]
Hi @mappuji,
It happens with your latest version. Maybe you test on the browser that has caches. 
I recommend you do your test following these steps:
1. Turn off your internet.
2. You have completely to quit your browser application.
3. Open a new incognito window and test.

**Comment by hikaruit15** [comment]
Hi @dogi,
According to MDWiki,
> MDwiki is a CMS/Wiki completely built in HTML5/Javascript and runs 100% on the client. No special software installation or server side processing is required. 

But its requirements:

> Webspace (or a web server that can serve static files)
> Any modern Webbrowser
> mdwiki.html file

They explain why we need a server in [FAQ question](http://dynalon.github.io/mdwiki/#!faq.md)

I use python3 on my mac  to test @mappuji  PR. 
```
python -m http.server 8080
```

**Comment by dogi** [comment]
htmlapp is when it run in a browser just by file:///... - no httpserver

in my turtle blocks case that is `file:///home/dogi/ole/turtleblocksjs/index.html`



PS: @mappuji in http://vi.ole.org:5999/resources/649ff1c7ed6d809eabe6d2165b000bf6/index.html left sidebar is acting strange ...

**Comment by mappuji** [comment]
@dogi sorry for misunderstood the definition of htmlapp. I have tried accessing in with `file://` and there is a problem with the jquery.

In the GitHub site of MDWiki, they said that accessing the wiki via browser is fixed in version 0.55, our current version of MDwiki is 0.62, but it can't open the wiki with `file://`. Currently, I have no idea to make it works in local with `file://` instead of via http server.

Here is the error I have:
```
jquery.min.js:2 XMLHttpRequest cannot load file:///C:/Users/Abdurrachman%20Mappuji/Development/open-learning-exchange/mappuji.github.io/navigation.md. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.
send @ jquery.min.js:2
jquery.min.js:2 XMLHttpRequest cannot load file:///C:/Users/Abdurrachman%20Mappuji/Development/open-learning-exchange/mappuji.github.io/config.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.
send @ jquery.min.js:2
jquery.min.js:2 XMLHttpRequest cannot load file:///C:/Users/Abdurrachman%20Mappuji/Development/open-learning-exchange/mappuji.github.io/index.md. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.
send @ jquery.min.js:2
VM33 index.html:176 [ERROR] unable to retrieve config.json: error
VM33 index.html:176 [FATAL] Could not get index.md
```

Anyone have a suggestion for me?

---

Second, for the turtle block js, could you give me a snapshot or log of error from javascript console @dogi ?

---

@hikaruit15 could you try it again? I believe it should work with web server who serve a static file (support http).

This is my screenshot of the mdwiki after following your suggestion.

image

It works in with web server but not working if we use it directly. I don't understand why. I think the turtle block also uses the jquery, but I don't know why it can't work in the mdwiki.

**Comment by hikaruit15** [comment]
Hi @mappuji,
I tried it on Firefox and Chrome again. But I still got the same result.
I used http server with port 8080.
**Firefox**
> screen shot 2017-02-02 at 6 05 34 pm

**Chrome**
> screen shot 2017-02-02 at 6 02 54 pm

**Comment by waryhermit** [comment]
@mappuji Have you given up on this pull request?

**Comment by waryhermit** [comment]
Since we accepted #483 this isn't needed anymore. If somebody disagrees it can be reopened.

**Pull request closed without merging**
