### PR TITLE
update mi-github-issues.md (fixes #3291)

### LINKED ISSUE #3291: mi-github-issues.md: old screenshot
### Problem
- pull request screenshots are outdated in mi-github-issues.md
  - https://open-learning-exchange.github.io/pages/mi/image/mi-compare-pull.png
  - https://open-learning-exchange.github.io/pages/mi/image/mi-pull-request-details.png

### Proposed solution

Replace with new ones

### PR DESCRIPTION
**Pull request by priya0030**
### Raw.Githack preview link
https://raw.githack.com/priya0030/priya0030.github.io/update-mi-github-issues.md(fixes-%233291)/index.html#!./pages/mi/mi-github-issues.md

### CODE REVIEW

**Comment by strawberrybread** [comment]
image

Can you change the `green` to `blue` to keep it consistent

**Comment by priya0030** [comment]
https://raw.githack.com/priya0030/priya0030.github.io/update-mi-github-issues.md(fixes-%233291)/index.html#!./pages/mi/mi-github-issues.md

**Review by strawberrybread — APPROVED** [review]

**Review by xyb994 — COMMENTED** [review]
Screenshot 2024-06-06 at 11 01 18 PM


The image looks kinda wide, could you crop it to something like this?
mi-compare-pull

**Comment by priya0030** [comment]
https://raw.githack.com/priya0030/priya0030.github.io/update-mi-github-issues.md(fixes-%233291)/index.html#!./pages/mi/mi-github-issues.md

here, i tried to resize the images multiple times and just take a look at it and let me know if it's going to work or not

**Comment by xyb994** [comment]
> https://raw.githack.com/priya0030/priya0030.github.io/update-mi-github-issues.md(fixes-%233291)/index.html#!./pages/mi/mi-github-issues.md
> 
> here, i tried to resize the images multiple times and just take a look at it and let me know if it's going to work or not

Turned out we need an empty line before and after the image for it to not show up as full size. I've updated the file.

**Pull request merged**
