### PR TITLE
Added divider between Windows installation directions and later directions

### PR DESCRIPTION
**Pull request by alan459**

### CODE REVIEW

**Comment by dogi** [comment]
@alan459 there are lot of files which have nothing to do with MDwiki which are commited by your 'pull request'

Please fix that and re-'pull request'

**Comment by alan459** [comment]
Yeah sorry I was trying to increase the spacing between the lines in the bughunt.md file but i ran into problems like grey boxes showing up around the text randomly so i undid those changes but the files remained changed because of the timestamps despite me undoing most of my work.

**Comment by alan459** [comment]
how can I request a pull for only 1 file, will i have to merge?

**Comment by dogi** [comment]
for example revert the commit where you checked in that stuff which has nothing to do with the MDwiki repo
then delete this non-MDwiki files
commit again
and then make an other `pull request`

**Comment by dogi** [comment]
https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/151

**Pull request closed without merging**
