### PR TITLE
Added onlyserenity.md

### PR DESCRIPTION
**Pull request by onlyserenity**
https://rawgit.com/onlyserenity/onlyserenity-ole.github.io/add-onlyserenity-profile/#!pages/vi/profiles/onlyserenity.md

### CODE REVIEW

**Comment by xyb994** [comment]
@onlyserenity Looks good overall, I made some small changes.

I'm curious to know where you get the rawgit link format from, it's missing `#!`, the right one is https://rawgit.com/onlyserenity/onlyserenity-ole.github.io/add-onlyserenity-profile/#!pages/vi/profiles/onlyserenity.md

**Comment by onlyserenity** [comment]
@xyb994 Sorry about that. I thought I just had to show the raw markdown, but I corrected now. Thanks!

**Comment by onlyserenity** [comment]
@xyb994 Is there a way to start a new line in markdown without the use of html tag i.g <br>?

**Comment by xyb994** [comment]
@onlyserenity depending on the "flavor" of Markdown, two spaces at the end of line, or one empty lines in between would do. There's no need for either of these in MDwiki.

**Pull request merged**
