### PR TITLE
Create tanmaysarin.md

### PR DESCRIPTION
**Pull request by tanmaysarin**
raw.githack.com/tanmaysarin/tanmaysarin.github.io/the-first-branch/#!pages/vi/profiles/tanmaysarin.md

### CODE REVIEW

**Comment by lmmrssa** [comment]
@tanmaysarin can you use some more markdown

**Comment by tanmaysarin** [comment]
Is it necessary to do so?

**Comment by lmmrssa** [comment]
@tanmaysarin the purpose of First steps are to help you learn basics required for project. And for us to see your progress. So it will be nice to see if you have learned more than just separator of markdown.

**Comment by lmmrssa** [comment]
Looks like not active anymore

**Pull request closed without merging**
