### PR TITLE
step 6 made clearer (#838)

### PR DESCRIPTION
**Pull request by kanishk1010**
[rawgit](https://rawgit.com/kanishk1010/kanishk1010.github.io/issue838/#!pages/firststeps.md)

- [x] Check for issue number in pull request title
- [x] Are there any unneeded files in the pull request?
- [x] Did they make a branch for their patch?
- [ ] Does the pull request actually fix the issue?
- [ ] Check the pull request on rawgit, does it display without any errors?
- [x] is there any merge conflicts?
- [x] Make sure that people use their GitHub accounts when making commits through git

### CODE REVIEW

**Comment by aurinsomnia** [comment]
I like the change, but I think the wording could use just a little tweak.

"Make sure you have created at least ~~an~~ **one** issue, ~~and~~ **solved it with** a pull request, **and merged** ~~with~~ the fix before proceeding to the next step."

This is just my initial thought, but let me know what you think!

**Comment by kanishk1010** [comment]
I agree with changing the wording and I would suggest further changes:
"Make sure you have created at least one issue, resolved it and have a pull request with the fix merged before proceeding to the next step."
Let me know what you think.

**Comment by aurinsomnia** [comment]
I agree, even better. Clear and concise. That's the wording I'd go with.

**Comment by kanishk1010** [comment]
Thanks for the advice. Will definitely keep that in mind in the future.  I have made multiple small changes throughout the paragraph, though.

**Pull request merged**
