### PR TITLE
Supriyaranjan patch 1

### PR DESCRIPTION
**Pull request by Supriyaranjan**
Created and added a new page "Supriyaranjan.md" in "Supriyaranjan-patch-1" branch. Please review it.

### CODE REVIEW

**Comment by sarvanivadali** [comment]
Hi @Supriyaranjan . Welcome! I think you missed few spaces in your headings.

**Comment by Supriyaranjan** [comment]
@sarvanivadali  thank you for your feedback. Can You please help me pointing out the exact Word/Sentance? Did you mean some spaces needed in Dallas,Tx(CST)?

**Comment by Supriyaranjan** [comment]
@dogi Sure

**Comment by sarvanivadali** [comment]
@Supriyaranjan Never mind my comments. Your earlier link did not render properly for me. Looks good now.

**Comment by dogi** [comment]
@i5o - good link ;)
on the other side we `squash merge` the PRs ...

**Comment by i5o** [comment]
@dogi well, she can try it and learn something new ;)

**Comment by Supriyaranjan** [comment]
@i5o I have squashed my commits with but how will it reflect in the pull request?

**Comment by i5o** [comment]
@Supriyaranjan thanks!
It will not affect the content of the pull request, but the organization of it or of the repo;
As dogi said this repository uses squash merge function to "push" the pull requests (so sorry D;); but in repos where it doesn't, you don't want to have 10 commits that lead to the same, ie:
c1 - Edit a.php
c2 - Edit a.php
c3 - Edit a.php

While you could just have
c1 - Added x thing to a.php

**Comment by i5o** [comment]
Also, don't forget to `git pull --force` once you rebase your commits so it's get reflected on the website

**Comment by Supriyaranjan** [comment]
@i5o - So I have done the squash merge and "git pull --force" to merge all changes into one change.

**Comment by i5o** [comment]
Agh my bad. It was git push --force.

Anyway, good job I'll merge the pull request

**Pull request merged**
