### PR TITLE
update link step8 (fixes #3396)

### LINKED ISSUE #3396: two different links leading to step 8
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md

### Problem

I found that the link from step 7 to step 8 is this: https://open-learning-exchange.github.io/#!./pages/vi/vi-create-issues-and-pull-requests.md

And if you're navigation from the first steps, the link is as follows: https://open-learning-exchange.github.io/#!./pages/vi/vi-issues-and-prs.md

The second link has more detailed on what issues we need to create, while the first one is more generic? I'm not sure which one is more updated, and also for people only follows the next link from each step, they may miss this.

### Screenshots (when necessary)

First Link:
Screenshot 2024-10-10 at 3 19 48 PM

Second Link:
Screenshot 2024-10-10 at 3 19 37 PM

### Proposed solution(s)

Changed both link to the same file, but I'm not sure which one is the intended file; Since one is more specific (requiring `issues` from specific manual/pages, and one is more generic, but they all asked for the same thing at the end.

### PR DESCRIPTION
**Pull request by RheuX**
**Important:** *Do not tick a checkbox if you haven’t performed its action.*

### Before Creating the Pull Request

- [x] Verify the changes are on a new branch other than `master` – it should say "compare: branch-name".
- [x] Start the pull request title with lowercase letters, e.g., `add githubusername.md`.
- [x] Add issue number to the end of the pull request title when applicable, e.g., `update mi-faq.md (fixes #3264)`.

### After Creating the Pull Request

- [x] Go to "Commits" tab, make sure the commit username is clickable and linked to your GitHub account correctly.
- [x] Review the "Files changed" tab to ensure there are no unnecessary files or changes included in the pull request.
- [x] Verify that the raw.githack preview link is included in the description.
  - [x] Preview the MDwiki rendered changes using the raw.githack link. Ensure it displays as expected without any errors.
- [x] Drop a link to this pull request in our discord channel.

### Description, Screenshots and/or Screencast

fixes #3396 

### Raw.Githack Preview Link

https://raw.githack.com/RheuX/RheuX.github.io/3396-update-link-step8/index.html#!pages/vi/vi-create-issues-and-pull-requests.md

https://raw.githack.com/RheuX/RheuX.github.io/3396-update-link-step8/index.html#!pages/vi/vi-first-steps.md

### CODE REVIEW

**Comment by RheuX** [comment]
I remove some information from `vi-issues-and-prs.md`, because i think its redudant to say it again, as there's the introduction, and also there some information that are on the `**NOTE**`. But please let me know if I should add that information back again

**Comment by RheuX** [comment]
Oh please give me a moment, I forgot to remove `vi-issues-and-prs.md`

**Review by xyb994 — APPROVED** [review]

**Comment by RheuX** [comment]
Before this is merge, can I ask if this is intended

`Ensure that at least one issue addresses content reduction, such as dead links, repetitive content, excessive detail, or the potential to reference external official documentation in Mobile Intern First Steps.`

In the last couple words, should it be Virtual Intern First Steps?

**Review by dogi — APPROVED** [review]

**Comment by xyb994** [comment]
> Before this is merge, can I ask if this is correct
> 
> `Ensure that at least one issue addresses content reduction, such as dead links, repetitive content, excessive detail, or the potential to reference external official documentation in Mobile Intern First Steps.`
> 
> In the last couple words, should it be Virtual Intern First Steps?

Oops, guess I missed this comment.

**Pull request merged**
