### PR TITLE
add coreyuw.md

### PR DESCRIPTION
**Pull request by coreyuw**
https://raw.githack.com/coreyuw/coreyuw.github.io/ole-coreyuw/#!pages/vi/profiles/coreyuw.md

### CODE REVIEW

**Comment by robinGiri** [comment]
@coreyuw your Raw.githack doesn't seems right and your are asked to use at least 5 different types of Markdown elements.

**Comment by lmmrssa** [comment]
@coreyuw Please do not touch _config file.
Your link will be https://raw.githack.com/coreyuw/coreyuw.github.io/ole-coreyuw/#!pages/vi/profiles/coreyuw.md

**Comment by lmmrssa** [comment]
@coreyuw Please do not touch _config file.
Your link will be https://raw.githack.com/coreyuw/coreyuw.github.io/ole-coreyuw/#!pages/vi/profiles/coreyuw.md

**Comment by coreyuw** [comment]
> @coreyuw Please do not touch _config file.
> Your link will be https://raw.githack.com/coreyuw/coreyuw.github.io/ole-coreyuw/#!pages/vi/profiles/coreyuw.md

Hi, I have added more Markdown syntax and reverted the changes in _config file

**Comment by coreyuw** [comment]
> @coreyuw your Raw.githack doesn't seems right and your are asked to use at least 5 different types of Markdown elements.

Hi, I have updated the raw.githack link, and added more Markdown elements. Thank you

**Pull request merged**
