### PR TITLE
Generate htmlapp via couchapp

### PR DESCRIPTION
**Pull request by mappuji**
This PR try to resolve the ide on issue #458 . I generate the html app via couchapp and it works. I have made the html app working offline and currently pushing it to the nation. It has size of 100 Mb but the connection to the nation is slow. I still waiting.

mdwiki-offline-1
mdwiki-offline-2

### CODE REVIEW

**Comment by hikaruit15** [comment]
Hi @mappuji Could you show the steps to test your PR?

**Comment by mappuji** [comment]
@hikaruit15 I am sorry, I have deleted my old fork of the open-learning-exchange wiki (due to complicated branching) and re-fork the repo. I will close this PR and raise the new PR with the test included.

**Comment by dogi** [comment]
@mappuji please do not close stuff

**Comment by dogi** [comment]
anyhow I understand that you have to redo this with this structure

```
tree vendor/
vendor/
├── ajax.googleapis.com
│   └── ajax
│       └── libs
│           └── jquery
│               └── 1.8.3
│                   └── jquery.min.js
├── netdna.bootstrapcdn.com
│   └── bootstrap
│       └── 3.0.0
│           ├── css
│           │   └── bootstrap.min.css
│           └── js
│               └── bootstrap.min.js
└── yandex.st
    └── highlightjs
        └── 7.3
            ├── highlight.min.js
            └── styles
                └── github.min.css
```

**Comment by mappuji** [comment]
I am sorry @dogi .
I just want to make the PR tab clean.

My point is, as I re-fork the repository, the rawgit I have provided no longer works.

**Comment by waryhermit** [comment]
I had tested it by pulling down the pull request via bash, so I could test it offline. I think that would still have worked even after you deleted your fork.

**Comment by mappuji** [comment]
Thank you for your feedback @waryhermit . Indeed, but I can't update or change file of this PR for further revision. I will re-do this and try @dogi suggestion about the skeleton.

**Pull request closed without merging**
