### PR TITLE
Fix indeed link (#1184)

### LINKED ISSUE #1184: Indeed link no longer works
## Problem
Links to indeed job description in following two places are no longer working:
<https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/pages/faq.md#q3-where-can-i-find-more-information-about-this-internship>

<https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/pages/firststeps.md#the-big-picture>

## Solution
It's likely caused by listing title change. Update the link to: 
<https://www.indeed.com/jobs?q=%22virtual%20remote%20software%20engineer%20intern%22&l=Cambridge%2C%20MA>

`[here on Indeed](https://www.indeed.com/jobs?q=%22virtual%20remote%20software%20engineer%20intern%22&l=Cambridge%2C%20MA)`

Or

get a [company page](https://www.indeed.com/hire/company-pages) and link to the company page's job section?

### PR DESCRIPTION
**Pull request by ajGingrich**
- [x] Check for issue number in pull request title
 - [x] Does the pull request actually fix the issue?
 - [x] Check the pull request on [rawgit](http://rawgit.com/ajGingrich/ajGingrich.github.io/fix-indeed-link/#!pages/firststeps.md), does it display without any errors?
 - [x] Is there any merge conflicts?

closes #1184

### CODE REVIEW

**Comment by kylemathias** [comment]
i agree with @Yurockkk .

**Comment by ajGingrich** [comment]
@Yurockkk @kylemathias I see that the pull request has been approved. How would you like me to approach resolving this? I can make a new issue if that is easiest.

**Comment by kylemathias** [comment]
@ajGingrich i think you can still edit the pull request even if its been approved. You can make the changes, and let us know and we will then approve those changes.

**Comment by ajGingrich** [comment]
I modified the link so that is now inline.

[rawgit](http://rawgit.com/ajGingrich/ajGingrich.github.io/fix-indeed-link/#!pages/faq.md)

**Pull request merged**
