### PR TITLE
Added a note to existing Github users to check their configurations.

### PR DESCRIPTION
**Pull request by sarvanivadali**
Adding a note to let existing Github users to check their configurations and fix email address as needed. This is for [issue/enhancement 508](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/508)

### CODE REVIEW

**Comment by sarvanivadali** [comment]
Hi @dogi do you think we need to re-word the note or is the note not necessary?

**Comment by dogi** [comment]
@sarvanivadali maybe? we should definitely think about that ... 

but first post the rawgit link here and ask other people of the team to review ;)

so we can brainstorm all together

**Comment by sarvanivadali** [comment]
Hi @dogi, all 
Here is the [rawgit](https://rawgit.com/sarvanivadali/sarvanivadali.github.io/ole_issue_508/#!pages/githubandmarkdown.md)

**Comment by waryhermit** [comment]
Hmm. I sort of feel like the people that would need to do this would be smart enough to figure it out themselves, but it doesn't take too much room. I'll let @dogi have the final say.

@sarvanivadali You could also make it look like the other `Note` in the same file.

**Comment by sarvanivadali** [comment]
Hi @waryhermit I will update my pull request with suggested markup and wait for @dogi 's response. I have a work email (from last internship) and personal email for OLE. I have realized that my initial pull requests accidentally have my work email in ```git log```. I could go back and change commit history. But learnt a lesson to check my ```git config``` before starting a new project :-)

**Comment by waryhermit** [comment]
@sarvanivadali Yeah, it might be a good change, I have no preference either way so I will let others have a chance to voice their opinions.

**Pull request merged**
