### PR TITLE
Fix issues #622 #633 

### PR DESCRIPTION
**Pull request by tianhaopx**
For issues #622 #633 

I looked the code of mdwiki website at https://github.com/Dynalon/mdwiki/tree/gh-pages. 
I found OLE website is using another version of jQuery and MDwiki.js. 
I just substituted these codes. 
Check the results here: http://rawgit.com/tianhaopx/tianhaopx.github.io/fix/#!pages/firststeps.md

### CODE REVIEW

**Comment by Supriyaranjan** [comment]
@tianhaopx Looks good to me. Let's see what others say about it.

**Comment by paulbert** [comment]
image

**Comment by paulbert** [comment]
When offline the navigation is not displaying correctly

**Comment by tianhaopx** [comment]
@paulbert The original one(without these changes) also doesn't work when offline. Because we are not using the default theme. 

> Note: Only the default bootstrap theme is bundled with MDwiki and available offline. All other themes require internet connection, as the styles are dynamically loaded on demand.

See http://dynalon.github.io/mdwiki/#!customizing.md

**Comment by tianhaopx** [comment]
@paulbert To fix this css issue is simple, just don't set theme in `navigation.md`. Check the latest change.

**Comment by paulbert** [comment]
@tianhaopx Ok, thanks.  We picked up on that from another commit.

Could you give some more information on what changed in the mdwiki.js script?  What did you do exactly to build this new index.html?  Did you copy and paste the old jQuery, colorbox, and mdwiki js files into the inline scripts?  Or did you do more?

There's a bit of added code into that script which, for example, adds target="_blank" to all external links.  I'm not seeing that in this version of the script.

**Comment by tianhaopx** [comment]
@paulbert 
For jquery and colorbox, I was changing them to old versions to fix #622. 
However, after reading your [comment](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/622#issuecomment-293311347) in #622, I switched back to new versions, and I added css for `width` according to your suggestion. See commit d0a59b0. I think it works now.

For mdwiki.js, I copy and pasted from latest release [MDwiki 0.6.2](https://github.com/Dynalon/mdwiki/releases/tag/0.6.2) to fix issue #633, which is not fixed in #626. I have added the js for external links in the commit 72bbe56.

**Comment by paulbert** [comment]
@tianhaopx Thanks for the clarification.  Based on what you had written on #633 we thought you were referencing the fact that in the markdown links on different pages were in different formats.  These are all the same in the markdown after #626, but there is a script which continually adds `./` to the front of links.  It's part of a [bugfix](https://github.com/Dynalon/mdwiki/issues/251) on the 0.6.x branch which was committed after the 0.6.2 release so isn't included in the file at https://github.com/Dynalon/mdwiki/releases/tag/0.6.2.

I had already incorporated some of these customizations into a fork of mdwiki, and just [posted a release](https://github.com/paulbert/mdwiki/releases) so you can grab the html without having to rebuild it.  That has a fix which will keep the bugfix for mdwiki and fix the urls adding `./` indefinitely.

**Comment by tianhaopx** [comment]
@paulbert I don't understand why we have to add `./` to the front of the links. Using code from 0.6.2 never adds `./`
wx20170412-153502 2x
wx20170412-153602 2x

**Comment by paulbert** [comment]
@tianhaopx The code was added as a security measure to prevent cross site scripting (XSS).  I'm not very familiar with that, so I am open to suggestions if you are aware of a different way to prevent this.  Ultimately, having the `./` added is a cosmetic issue on the URL and won't affect the site, so it doesn't seem worth it to roll back a security improvement to fix a cosmetic issue.

The function is at line 405 of [this file](https://github.com/paulbert/mdwiki/blob/0.6.x/js/main.js) and the specific code (which adds the `./` to the start of the file before it is loaded, not to all of the links) is lines 406 to 411.  I believe it's because the navigation is loaded from a different markdown file that the links there do not have the `./` added.

Please let me know if you have a solution which would solve the cosmetic issue without removing the XSS fix.

**Comment by tianhaopx** [comment]
@paulbert 
Thanks for the explanation. I don't have new ideas for XSS fix. So I changed back mdwiki.js. 

What about merge this pull request to fix the side menu issue? We can leave the URL issue and discuss with others later.

**Comment by paulbert** [comment]
Ok sounds good.  I'll merge this and create a PR for #673

**Pull request merged**
