### PR TITLE
Add Paul Albert (paulbert) page

### PR DESCRIPTION
**Pull request by paulbert**

### CODE REVIEW

**Comment by waryhermit** [comment]
Hey @paulbert,

I see that you committed directly to your master branch. Did you just miss the directions for making a branch for your page or are the directions in need of improvement do you think? (That sounds a little sarcastic, but its a serious question, its hard to made good directions.)

In this case it won't matter that much, but in the future it could bite you in the butt.

**Comment by paulbert** [comment]
Hi @waryhermit,
I did see the directions, but I had merged it into the master on my fork to make the the page appear on paulbert.github.io

Is there another step I could have taken to have the live page work without merging?  If so, then I'd suggest we add that to the directions (also not sarcastic, and I totally understand directions are hard).  The GitHub pages settings only seem to allow it to be built from the master branch, though.

**Comment by dogi** [comment]
@waryhermit good point - we fix this a while ago https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/433

now I have to remember to watch out for this ...

**Comment by dogi** [comment]
@paulbert good point 

> Is there another step I could have taken to have the live page work without merging? If so, then I'd suggest we add that to the directions (also not sarcastic, and I totally understand directions are hard). The GitHub pages settings only seem to allow it to be built from the master branch, though.

**Pull request merged**
