### PR TITLE
Fix indeed link (#1184)

### LINKED ISSUE #1184: Indeed link no longer works
## Problem
Links to indeed job description in following two places are no longer working:
<https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/pages/faq.md#q3-where-can-i-find-more-information-about-this-internship>

<https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/pages/firststeps.md#the-big-picture>

## Solution
It's likely caused by listing title change. Update the link to: 
<https://www.indeed.com/jobs?q=%22virtual%20remote%20software%20engineer%20intern%22&l=Cambridge%2C%20MA>

`[here on Indeed](https://www.indeed.com/jobs?q=%22virtual%20remote%20software%20engineer%20intern%22&l=Cambridge%2C%20MA)`

Or

get a [company page](https://www.indeed.com/hire/company-pages) and link to the company page's job section?

### PR DESCRIPTION
**Pull request by ajGingrich**
- [x] Check for issue number in pull request title
 - [x] Does the pull request actually fix the issue?
 - [x] Check the pull request on rawgit, does it display without any errors?
 - [x] Is there any merge conflicts?

closes #1184

### CODE REVIEW

**Comment by dogi** [comment]
@ajGingrich awesome ;)

Anyhow if it had a working rawgit link I would have already reviewed it ...

**Comment by dogi** [comment]
https://rawgit.com/ajGingrich/ajGingrich.github.io/fix/indeed-link/#!pages/firststeps.md is not working ... cause `fix/indeed-link` as branch name is breaking rawgit logic

@open-learning-exchange/virtual-interns and @ajGingrich wonder if we should create an issue to say do not use `/` and maybe other characters as branchnames cause they make difficulties when used with rawgit ;)
maybe that is overkill and @ajGingrich just makes an other branch branched of this PR branch which has no special character ....

**Comment by Yurockkk** [comment]
@dogi as I remember, having `#` in the branch name also break rawgit logic

**Comment by ajGingrich** [comment]
@dogi The rawgit works fine for me for some reason. I'll make a more appropriately named branch and submit a different PR.

**Comment by dogi** [comment]
> @dogi The rawgit works fine for me for some reason. I'll make a more appropriately named branch and submit a different PR.

@dogi is confused now ;)

@ajGingrich which rawgit link did you use?

**Comment by ajGingrich** [comment]
@dogi I was using the same that you posted above:  https://rawgit.com/ajGingrich/ajGingrich.github.io/fix/indeed-link/#!pages/firststeps.md. 

Now it obviously doesn't work for either us because I deleted the branch 😮

**Pull request closed without merging**
