### PR TITLE
Added Intern Orientation to Teams Menu

### PR DESCRIPTION
**Pull request by kylemathias**
#552 this should solve this issue.

### CODE REVIEW

**Comment by Supriyaranjan** [comment]
@kylemathias  Hi.. I saw your changes and looks good to me. Even I created a pull request for the same issue and I am guessing you have added the menu item in the start of drop down and I have added it in the end

**Comment by kylemathias** [comment]
I messed it up, i waws trying to put in a pull request for issue #432 . i was trying to revert it and i made more of a mess. sorry.

**Comment by waryhermit** [comment]
@kylemathias Its OK, people do this fairly often, its a good learning experience.

**Comment by kylemathias** [comment]
Closing it so i dont ever have to look at this mess i made again. =P

**Pull request closed without merging**
