### PR TITLE
Add browser recommendation to top of page (fixes #1986)

### LINKED ISSUE #1986: Firefox Browser Doesn't Scroll to Top After Clicking on Link
### Problem
Firefox automatically scrolls to a random point in the page when clicking on external links. 

### Steps to reproduce the problem

1. Open Firefox, and navigate to [first steps](http://open-learning-exchange.github.io/#!./pages/vi/vi-first-steps.md#Step_4_-_BeLL-Apps_and_Planet_Tutorial)
2. Scroll to "Step 2" and click on __Planet Installation and Configuration__.
3.  Note that you will be automatically scrolled to some mid point on the page. (See pic below)
4. Try this for all other links.

### Where my browser scrolls to after clicking "__Planet Installation and Configuration__"
image

### Proposed solution

This seems to be browser specific to Firefox, as this is not an issue on Chrome.  Not sure how to fix this or where to start but here is a helpful link I've found:
* [Prevent Automatic Autoscroll](https://stackoverflow.com/questions/7035331/prevent-automatic-browser-scroll-on-refresh)

Other option would be to recommend in "The Big Picture" to go through instructions using Chrome.

### PR DESCRIPTION
**Pull request by jimkosh**
Fixes #1986 

### Description
Added browser(Chrome) recommendation for "First Steps" in "Big Picture" section because there are bugs using Firefox.

### RawGit preview link

[Rawgit](https://rawgit.com/jimkosh/jimkosh.github.io/add_browser_recommendation/#!pages/vi/vi-first-steps.md)

### CODE REVIEW

**Comment by lmmrssa** [comment]
@jimkosh rawgit link invalid

**Comment by jimkosh** [comment]
@lmmrssa fixed Rawgit link here too :)

**Comment by lmmrssa** [comment]
@jimkosh instead of adding it on big picture could you add it when steps starts. On big picture there are not any links related to project.

**Comment by jimkosh** [comment]
@lmmrssa got it

**Pull request merged**
