### PR TITLE
Optimize image assets

### PR DESCRIPTION
**Pull request by blakedelee**
Reduction in size from 50%-80%, sizable improvement to page-load speed

See issue #538

### CODE REVIEW

**Comment by hikaruit15** [comment]
@blakedelee it's a good idea :)

**Comment by mappuji** [comment]
@blakedelee You give such a good idea. From my perspective, the size not reducing the quality which is good.

Waiting for inspection of others.

**Comment by dogi** [comment]
@blakedelee sorry to join this conversation so late - good job ;)

I have two more questions ...
- since you worked on all the pictures I assume you did work with a script or tool to automatize this process ... anyhow can you describe more what you did
- wonder also how this PR influences the size of our github repo

**Comment by blakedelee** [comment]
I used [pngquant](https://pngquant.org/) to compress the images.  A rough estimate in the change in size of the repo on my machine was ~5 MB.

**Pull request merged**
