### PR TITLE
changed formatting and structure of team.md (#854)

### PR DESCRIPTION
**Pull request by kanishk1010**
[rawgit link](https://rawgit.com/kanishk1010/kanishk1010.github.io/issue854/#!pages/team.md) 

- [ ] Check for issue number in pull request title
- [ ] Are there any unneeded files in the pull request?
- [ ] Did they make a branch for their patch?
- [ ] Does the pull request actually fix the issue?
- [ ] Check the pull request on rawgit, does it display without any errors?
- [ ] is there any merge conflicts?
- [ ] Make sure that people use their GitHub accounts when making commits through git

### CODE REVIEW

**Comment by aurinsomnia** [comment]
So I think this definitely looks nicer, but it might cause a little confusion of the differences between volunteers and interns. I can't really make a call on whether this is appropriate or not, so I'll turn to other admins on this one.

**Comment by kanishk1010** [comment]
@aurinsomnia Yeah I took some liberty in changing the organization and structure. Markdown doesn't afford a lot of options with formatting. I would appreciate any suggestions @Loshma93 @kylemathias.

**Comment by ChenjieZhou** [comment]
@kanishk1010 Maybe you could change css file directly, but it might lead to additional problems.

**Comment by kylemathias** [comment]
@Loshma93 @sarah-lu102 was this merged before they were done? im confused, the rawgit doesn't even work and this got merged and approved...

**Comment by sarah-lu102** [comment]
I think the tables looked ok- even though the columns of the first table and second don't line up, it should be fine since they don't have the same number of columns anyway.

**Pull request merged**
