### PR TITLE
Update planetusermanual.md Library and Resources Overview

### PR DESCRIPTION
**Pull request by Loshma93**

### CODE REVIEW

**Comment by waryhermit** [comment]
@Loshma93 You need to add the images to this pull request

**Comment by Loshma93** [comment]
@waryhermit How can I add images to this PR after creation??

**Comment by waryhermit** [comment]
@Loshma93 Just update the branch - all changes on that branch will be automatically added to the pull request. Github even has a little note above the conflict warning: "Add more commits by pushing to the Loshma93-patch-8 branch on open-learning-exchange/open-learning-exchange.github.io."

**Comment by Loshma93** [comment]
add collection
collection
main collection
new resource
save

**Comment by waryhermit** [comment]
@Loshma93 Yes, but they should be located at `pages/uploads/images`

**Pull request merged**
