### PR TITLE
Issue and pull request template (fixes #1702)

### LINKED ISSUE #1702: Create Issue and Pull Request template
https://help.github.com/articles/creating-an-issue-template-for-your-repository/
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

https://github.com/open-learning-exchange/open-learning-exchange.github.io/commits/issue-and-pr-template

### PR DESCRIPTION
**Pull request by xyb994**
Issue #1702

Please add your suggestions or comment on the template

### CODE REVIEW

**Comment by sahilph** [comment]
Looks good 👍

**Comment by sahilph** [comment]
@xyb994 
I have made some changes to the issue template to maintain the template format. Please check.

**Comment by xyb994** [comment]
@sahilph 
Is it necessary to have "Steps to reproduce the problem" for the issue template that primarily deal with Markdown content?

**Comment by sahilph** [comment]
@xyb994 Its for the technical issues that might arise while installation of bell or planet or any other technical issues which can be fixed.

**Comment by xyb994** [comment]
@sahilph Those issue should probably go into their own respective repositories.

**Comment by sahilph** [comment]
@xyb994 
No I meant like these issues. For example. Check these previous PRs. #1683, #1675 and their respective issues #1680, #1663 
I think it would be better if we know the steps to get to a problem, It would help for a quicker analysis.

**Comment by xyb994** [comment]
@sahilph Ok, yeah it does not hurt to have it there. 

@kylemathias Yeah, we should probably update some screenshots and paragraphs. The comments in those templates also reinforce the check list we have in First steps since sometimes people forget to or do not follow them. I'm not sure if we should include everything we check in the template though.

**Pull request merged**
