### PR TITLE
About me

### PR DESCRIPTION
**Pull request by kanishk1010**
rawgit_screenshot

Following subsequent changes were made after the initial version:

 * Formatted my technical experience in tabular form
 * Added my non-technical interests with a fun-fact and an image
 * Used Gimmick for text highlighting
 * Other minor formatting changes

### CODE REVIEW

**Comment by kanishk1010** [comment]
rawgit_screenshot

Following subsequent changes were made after the initial version:

 * Formatted my technical experience in tabular form
 * Added my non-technical interests with a fun-fact and an image
 * Used Gimmick for text highlighting
 * Other minor formatting changes

**Comment by kylemathias** [comment]
@sarah-lu102 please review the page before you merge.

**Comment by snazzybunny** [comment]
Looks pretty good to me.

**Comment by sarah-lu102** [comment]
@kylemathias sorry, I tried to approve after I merged but I realized I had to approve beforehand.

**Pull request merged**
