### PR TITLE
first Markdown file Leslie569.md

### PR DESCRIPTION
**Pull request by Leslie569**
rawgit link: https://raw.githack.com/Leslie569/Leslie569.github.io/lwang/#!pages/vi/profiles/Leslie569.md
On MDwiki, The emojis don't appear as they do in github's preview.

### CODE REVIEW

**Comment by lmmrssa** [comment]
@Leslie569 Looks like you have used lot of emoji. There is a note written on Markdown page to use the actual emoji icon instead of emoji shortcode, because of the same reason you mentioned. Could you try to change it to copy actual emoji icon.

**Comment by Leslie569** [comment]
I replaced all the codes, but it seems like the problem was not resolved.

**Comment by Leslie569** [comment]
I saw it just now, guess there was a delay after I changed the file. May I ask another question: why there is a table beside the image containing all the subtitles on https://raw.githack.com/Leslie569/Leslie569.github.io/lwang/#!pages/vi/profiles/Leslie569.md? It's not in the preview though.

**Comment by lmmrssa** [comment]
@Leslie569 That is because of the tag you used. Our standard template for this repository will convert that`---` tag as side menu to provide navigation to those points easier.

**Comment by Leslie569** [comment]
I see. Thanks for the explanation. I just replaced all the `---` tags. Is my pull request eligible for merging now?

**Pull request merged**
