### PR TITLE
Simpleinstall.md Spelling

### PR DESCRIPTION
**Pull request by zeivhann**
#582 
Third time is the charm, right?
Apparently what I had done was first made a branch of the first branch I made.
Then I somehow merged that first branch I made with the master branch.

So I fixed it by deleting the branches I messed up on, rebased by main branch and reset it so it is exactly like the [main branch](https://github.com/open-learning-exchange), and then made a new branch from there. So it might look a little strange, but I believe that this is what I should have submitted in the first place. :P

### CODE REVIEW

**Comment by zeivhann** [comment]
@dogi I am a native English speaker and I think your English is great! Thanks!

**Comment by waryhermit** [comment]
@zeivhann @dogi 
I don't remember having ever seen this page? Where can you get to it from the MDWiki? Or is it an unused page?

**Comment by zeivhann** [comment]
It is under Teams > Simple Install.

**Comment by waryhermit** [comment]
@zeivhann Oh yeah, thanks..

**Pull request merged**
