### PR TITLE
Create NirmalKumarJoshi.md

### PR DESCRIPTION
**Pull request by NirmalKumarJoshi**
https://rawgit.com/NirmalKumarJoshi/NirmalKumarJoshi.github.io/add-NirmalKumarJoshi-profile/pages/vi/profiles/void.md

### CODE REVIEW

**Comment by xyb994** [comment]
@NirmalKumarJoshi 

- Any particular reason you are naming the file `void.md`? It will be hard to know it's you.
- https://rawgit.com/NirmalKumarJoshi/NirmalKumarJoshi.github.io/add-NirmalKumarJoshi-profile/#!pages/vi/profiles/void.md is the right rawgit link that you can view the full MDwiki version of the page. Is there anything you would like to change to make it clearer?

**Comment by NirmalKumarJoshi** [comment]
No I don't have to make any more changes.

**Comment by sahilph** [comment]
@NirmalKumarJoshi Your file name should be same as your github username. Please change it.

**Comment by NirmalKumarJoshi** [comment]
@sahilph Done.

**Comment by NirmalKumarJoshi** [comment]
Added more spaces in description section.

**Pull request merged**
