### PR TITLE
Change community manage page image (Issue #982)

### PR DESCRIPTION
**Pull request by tjyothsna16**
Rawgit <a href="http://rawgit.com/tjyothsna16/tjyothsna16.github.io/change-community-manage-page-image/#!pages/nation.md">here</a>.
Issue #982.

### CODE REVIEW

**Comment by kylemathias** [comment]
Can you crop the image? try and make it the same size as the original.

**Comment by tjyothsna16** [comment]
Sure. That makes sense.

**Comment by navneetkarnam** [comment]
* @tjyothsna16 Are you still working on this PR??

**Comment by tjyothsna16** [comment]
@navneetkarnam Yes, I am working on this.

**Comment by tjyothsna16** [comment]
@aurinsomnia @navneetkarnam Please take a look at my recent changes. I have updated all images but 2 with the latest ones. One of the 2 images that I did not change looks latest enough to me. The other image I did not change is Dogi's Vi Nation Bell homepage.

**Pull request merged**
