### PR TITLE
Update myPlanet User Manual in Admin User Manual

### LINKED ISSUE #2700: Update myPlanet User Manual in Admin User Manual
# Problem
There is no content in myPlanet User Manual.

### Steps to reproduce the problem
N/A

### Screenshots
myPlanet-user

### Proposed solution
Delete myPlanet User Manual menu or Adding some content

### PR DESCRIPTION
**Pull request by pattanawadee88**
Fixes #2700 

### Description
Update myPlanet User Manual in Admin User Manual
*Add "we are in the process of updating this page" 

### Raw.Githack preview link
https://raw.githack.com/pattanawadee88/pattanawadee88.github.io/pat-pat/#!./pages/manual/myplanet/overview.md

[x] Check for issue number in pull request title
[x] Are there any unneeded files in the pull request?
[x] Did they make a branch for their patch?
[x] Does the pull request actually fix the issue?
[x] Check the pull request on raw.githack, does it display without any errors?
[x] Is there any merge conflicts?
[x] Make sure that people use their GitHub accounts when making commits through git

### CODE REVIEW

**Comment by pattanawadee88** [comment]
> Just a minor error. There is a space between the last word and the exclamation point. Please fix that and it will be ready to go.

I fixed it.

**Comment by pattanawadee88** [comment]
> you created branch out of branch not from master branch. Please make sure that you keep your master branch up to date and create branch from there.

Do I need to fix that?

**Comment by lmmrssa** [comment]
> > you created branch out of branch not from master branch. Please make sure that you keep your master branch up to date and create branch from there.
> 
> Do I need to fix that?

yes please

**Comment by smitshrestha101** [comment]
I was thinking about making some updates to this page too. Great job!

**Comment by pattanawadee88** [comment]
> > > you created branch out of branch not from master branch. Please make sure that you keep your master branch up to date and create branch from there.
> > 
> > 
> > Do I need to fix that?
> 
> yes please

I fixed this issue. Please review. Thank you! 

https://raw.githack.com/pattanawadee88/pattanawadee88.github.io/new-branch/#!./pages/manual/myplanet/overview.md

**Pull request closed without merging**
