### PR TITLE
mouthz.md

### PR DESCRIPTION
**Pull request by mouthz**

### CODE REVIEW

**Comment by sarvanivadali** [comment]
Hi @mouthz I like your changes. Is it possible to post a rawgit link here? (It really helped me during my vetting process to speed up review process).

**Comment by mouthz** [comment]
Yes, no problem. I'll start on it right away once I get home.

**Comment by waryhermit** [comment]
@sarvanivadali For very simple markdown files the built-in github preview works pretty well. Not that its bad to get people in the habit I suppose

**Comment by hikaruit15** [comment]
@mouthz great!

**Pull request merged**
