### PR TITLE
Updated and improved team page issue #408

### PR DESCRIPTION
**Pull request by IshanSoni**

### CODE REVIEW

**Comment by dogi** [comment]
@IshanSoni 2 things:

- @i5o was also a teamlead ;) just look at his personal page you will understand ...
- love the last lines but think we need to move them up somewhere between Current VI and VI summer 2016

**Comment by IshanSoni** [comment]
@dogi Should I add the last line on top of the page instead?

**Comment by i5o** [comment]
Just wondering, is there anything I can do to help?
Summer is about to start and I will have free time, so if there is
anything that I can help with, I would love to :)

Thanks ;D

2016-12-15 13:51 GMT-03:00, dogi <notifications@github.com>:
> @IshanSoni 2 things:
>
> - @i5o was also a teamlead ;) just look at his personal page you will
> understand ...
> - love the last lines but think we need to move them up somewhere between
> Current VI and VI summer 2016
>
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/411#issuecomment-267379234


-- 
Ignacio Rodríguez

**Comment by cpanican** [comment]
I think we should put "Steps in progress" for current virtual interns as well. Maybe we should ask them for a PR of their name before step#8. It also keeps track of people who actually makes it that far in the First Steps.

**Comment by dogi** [comment]
@cpanican you are funny ;)
but no realistic

**Comment by dogi** [comment]
@i5o :) - just join the gitter channel again...

**Pull request merged**
