### PR TITLE
I added ole logo which would bring users to ole.org 

### PR DESCRIPTION
**Pull request by fsjoyti**
Trying to resolve issue #39

### CODE REVIEW

**Comment by dogi** [comment]
Interesting attempt with 2 isses:

* picture link should be relative one (e.g. /ll_CC/pages/uploads/images/something.png) and not something foreign like https://i.imgsafe.org
* would like this logo smaller and before the virtual intern menu entry

**Comment by fsjoyti** [comment]
Hi dogi I modified the link to make it a relative link and I made the image smaller. However, I am confused about how to put it before virtual interns

**Comment by dogi** [comment]
Thanks for trying - I think for adding a logo before "virtual interns" you need to do this in following file

https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/ll_CC/index.html

**Comment by fsjoyti** [comment]
Thanks I will try to look into that

**Pull request closed without merging**
