### PR TITLE
PR for updating vagrant tutorial page (issue 981)

### PR DESCRIPTION
**Pull request by navneetkarnam**
- This PR fixes issue #981 
- Here is the rawgit [link]( https://rawgit.com/navneetkarnam/navneetkarnam.github.io/navneetkarnam-patch-4/#!pages/vagrant.md)

### CODE REVIEW

**Comment by navneetkarnam** [comment]
@aurinsomnia Yup! I got that and corrected it :)

**Comment by sarah-lu102** [comment]
something like this capture

**Comment by navneetkarnam** [comment]
@sarah-lu102 sure... I'll change that :)

**Comment by navneetkarnam** [comment]
@sarah-lu102 I made the formatting. It looks better now. Thank you :)

**Pull request merged**
