### PR TITLE
Intern profile folder

### PR DESCRIPTION
**Pull request by yssdnj**
Move all intern profile .md file under page folder to Intern_Profile folder. Make layout clear

### CODE REVIEW

**Comment by mappuji** [comment]
Hi @yssdnj it is actually a good idea, but you create a lot of changes when doing this.
Please wait for @dogi 's consideration

**Comment by yssdnj** [comment]
Yes, there are lots of changes. And if so, the corresponding content in [GitHub and Markdown page](http://open-learning-exchange.github.io/#!./pages/githubandmarkdown.md) also need to change.

**Comment by waryhermit** [comment]
>Yes, there are lots of changes. And if so, the corresponding content in GitHub and Markdown page also need to change.

@yssdnj This pull request does not make those changes correct? If so this pull request would break the MDwiki..

**Comment by yssdnj** [comment]
@waryhermit First thing I'd like to make sure is that do we plan to reorganize the page folder. If so, we could try to think out some methods and impliment the optimal one.

**Comment by waryhermit** [comment]
@yssdnj Sounds good - that is what issue https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/568 is for. If you have any thoughts on what the best method would be add them there. 😺

**Comment by yssdnj** [comment]
@waryhermit Yes, I will. So I close this PR?

**Comment by waryhermit** [comment]
@yssdnj Sure, we can close it for now to keep things clean. If you have a full solution sometime, feel free to make a pull request for it.

**Comment by yssdnj** [comment]
@waryhermit  No problem.

**Pull request closed without merging**
