### PR TITLE
Update html5 resource link in faqs for vi section (Fixes #2991)

### LINKED ISSUE #2991: Faq helpful link leads to tutorial `not in use`
### Problem
Tutorial for html5 that is in helpful links is not in use by w3schools as indicated by the page title 
`Not In Use`

### Steps to reproduce the problem
Go to [virtual Interns FAQ](https://open-learning-exchange.github.io/#!./pages/vi/vi-faq.md#General_Internship_Questions) Helpful links section. Click on [HTML5 tutorial](https://www.w3schools.com/html/html5_intro.asp)

### Screenshots
issuefaqlinks
issuefaqlinks2
issuefaqlinks3

### Proposed solution
Update the html5 resource link with the current in use tutorial from [w3schools](https://www.w3schools.com/html/default.asp)

### PR DESCRIPTION
**Pull request by Mutugiii**
Fixes #2991 

### Description
Update the html5 link in the [virtual interns faq helpful links](https://open-learning-exchange.github.io/#!pages/vi/vi-faq.md) to an updated one by w3schools

### Raw.Githack preview link
[Raw Githack preview link](https://raw.githack.com/mutugiii/mutugiii.github.io/fix/issue-faq-link/#!pages/vi/vi-faq.md)

### CODE REVIEW

**Comment by jsschf** [comment]
Hey @Mutugiii I addressed this in my PR #2990. It wasn't in my original issue that the PR is based off of, I added a comment to the issue after I posted it (issue #2985). I apologize for any confusion, I should've waited until I looked over everything in the FAQ before I posted the issue.

**Comment by Mutugiii** [comment]
@jsschf No worries about that.

**Comment by Mutugiii** [comment]
@LordJashin32 Thanks for that, I went over it and made sure the commit is verified

**Comment by singharpita** [comment]
@LordJashin32 please review

**Pull request merged**
