### PR TITLE
changed screen shot (fixes #2975)

### LINKED ISSUE #2975: Unclear screenshot in Actions on List Page
**Problem:**
Unclear screenshot in Actions on List Page .

**Steps to reproduce the problem:**
Going to [Courses, under Planet Manual](https://open-learning-exchange.github.io/#!./pages/manual/planet/./course.md)

**Screenshots:**

sourting courses screenshot it confusing 1

**proposed solution:**

Update screenshot, removing the pop up box to the right.

### PR DESCRIPTION
**Pull request by chtelmko**
Fixes #2975

### Description
Changed screen shot for better clarity.

### Raw.Githack preview link
https://raw.githack.com/chtelmko/chtelmko.github.io/screenshot/#!pages/manual/planet/course.md

### CODE REVIEW

**Comment by chtelmko** [comment]
I am sorry, i thought i fixed it by re-cloning it to  my machine. should i delete my chtelmko repository and re-fork it?

**Comment by lmmrssa** [comment]
@chtelmko it is not related to repository clone. It is related to config on your machine for github. on one of your pr i had written where you need to look for the setting. or you can look for how to setup github config on local machine to reflect your account on commit

**Comment by chtelmko** [comment]
Yes, thank you for that. I remember it was on step 3. I will try to follow it again. but i already went though it.

**Comment by chtelmko** [comment]
Thank you for a quick reply

**Pull request closed without merging**
