### PR TITLE
Update planetusermanual.md- courses section

### PR DESCRIPTION
**Pull request by sarah-lu102**
*Editid by @mappuji*
See the rawgit [here](https://rawgit.com/sarah-lu102/sarah-lu102.github.io/sarah-lu102-courses-patch/index.html#!pages/planetusermanual.md)

### CODE REVIEW

**Comment by dogi** [comment]
@waryhermit agree ;)

@sarah-lu102 it would be awesome if you could at least change this pic https://github.com/sarah-lu102/sarah-lu102.github.io/blob/9bff28e2537fa40683abf24906d672138944bb1b/pages/uploads/images/addstep.png

**Comment by sarah-lu102** [comment]
how do I resolve the branch's conflicts?

**Comment by waryhermit** [comment]
@sarah-lu102 https://help.github.com/articles/resolving-a-merge-conflict-on-github/

**Comment by sarah-lu102** [comment]
resolved!

**Comment by sarah-lu102** [comment]
fixed!

**Comment by dogi** [comment]
@sarah-lu102 oops just saw there is a merge conflict - please resolve that ;)

**Comment by sarah-lu102** [comment]
@dogi resolved!

**Comment by lmmrssa** [comment]
@dogi From what I see in this PR, its the document for old course structure. So we might have to update this Course page once we release new Course structure.

**Comment by sarah-lu102** [comment]
@dogi maybe you can merge the pr now and we can edit it later?

**Pull request closed without merging**
