### PR TITLE
yosry95.md profile

### PR DESCRIPTION
**Pull request by yosry95**
https://github.com/yosry95/yosry95.github.io/blob/tryingMarkdown1/pages/vi/profiles/yosry95.md

### CODE REVIEW

**Comment by ketruong** [comment]
Add raw git link please. For example: 
https://rawgit.com/ketruong/ketruong.github.io/test_branch/#!pages/vi/profiles/ketruong.md

**Comment by yosry95** [comment]
Thank you i have change it

**Comment by yosry95** [comment]
https://rawgit.com/yosry95/yosry95.github.io/tryingMarkdown1/#!pages/vi/profiles/yosry95.md

**Comment by yosry95** [comment]
I have changed the code but it hasn't been updated on the link above.
What shall I do?

**Comment by ketruong** [comment]
It's most likely a cache issue. Try a different browser or clear the cache.

**Comment by ketruong** [comment]
Can you capitalize your I's and change "language that i have good knowledge at" to "Languages that I know very well"? Also can you change "projects that has been done" to "Projects that I've done"? Thanks.

**Comment by yosry95** [comment]
I have changed them :D
https://rawgit.com/yosry95/yosry95.github.io/tryingMarkdown1/#!pages/vi/profiles/yosry95.md

**Comment by ketruong** [comment]
Two small things left: just change language to Languages and projects to Projects. Looks good!

**Comment by yosry95** [comment]
Done :smile:

**Pull request merged**
