### PR TITLE
add bradlet.md

### PR DESCRIPTION
**Pull request by bradlet**
https://raw.githack.com/bradlet/bradlet.github.io/bradletFirstSteps/#!pages/vi/profiles/bradlet.md

### CODE REVIEW

**Comment by bradlet** [comment]
Please ignore all changes / inclusions to this pull request outside of my personal .md file, bradlet.md.

I moved the docker-tutorial changes to its own branch as per @SNutakki 's suggestion.

**Comment by ChiragAwale** [comment]
@bradlet You should create a new branch for each Pull Request. It seems you are pushing all commits to the same branch. Thus every change is in this branch currently.

**Comment by lmmrssa** [comment]
Also use some more markdown

**Comment by bradlet** [comment]
@lmmrssa I am going to be deleting this branch since I made the mistake of including my later-step changes in this branch. I already made a separate pull-request that has been merged for those changes on a separate branch. I am going to be simply making a new branch, dropping my bradlet.md file (with a few more markdown elements as-per your request), and then making a new pull request so the branch isn't muddled with other stuff.

**Pull request closed without merging**
