### PR TITLE
Chat add i446

### PR DESCRIPTION
**Pull request by Chris-Boe**
Added description of Gitter chat on [chat](http://open-learning-exchange.github.io/#!pages/chat.md). Issue [446](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/446)

### CODE REVIEW

**Comment by dogi** [comment]
In http://rawgit.com/Chris-Boe/Chris-Boe.github.io/chat_add_i446/#!pages/chat.md
you can see how it looks like

Saw already that you followed some of the adivises made in
https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/446#issuecomment-280016546

@waryhermit @hannahgdubin @hikaruit15 @mappuji tell us what you think

@dogi has the feeling that it would be better to move some of this text after the `<iframe>`

**Comment by Chris-Boe** [comment]
@dogi, how about I move the preview to right after the first paragraph? And I forgot to add the stuff about the mobile app so I'll do that real quick :)

**Comment by hikaruit15** [comment]
Hi @dogi, @Chris-Boe 
In my opinion, it is not necessary to add a long paragraph to Chat page. This description explain the function of Chat page for new interns who are not familiar with it. 
Because new interns have to use gitter chat to interact with us. So my suggestion is if we need to explain Chat page, we should add information to `First steps`.

**Comment by Chris-Boe** [comment]
@dogi , @hikaruit15 ,
The First Steps intro is already jam-packed with info (especially after some [suggested edits](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/481) ).
I still think it would be nice to have this info on the chat page, so that the candidates can see the chat as they read about chat etiquette and the importance of the Gitter chat.
If we had this info on the chat page, we could also shorten the [First steps](http://open-learning-exchange.github.io/#!pages/firststeps.md) Introduction, and instead add a "Be sure to get familiar with how to use the Gitter Chat" type of instruction in the "Step 0" section.

**Comment by waryhermit** [comment]
I certainly agree the first steps doesn't need any clutter. There should be an absolute minimum on the chat page as well. I know I never even went there, so we can't count on anyone having read it.

**Comment by hannahgdubin** [comment]
I think that it is a good idea to add the description into the chat page however it seems repetitive to have it say the same thing in the first steps page and in the chat page. I think it might be useful to change the first steps page. Instead of saying this (see below) in the first page we may just want to "say please refer to the chat page fro more information on how to communicate in gitter" 
 > We also want you to keep us updated a relatively good amount in the Gitter chat as you complete these steps. Generally, you should comment in the Gitter chat when you make an issue or pull request, and then link to it. It's also good form to mention someone in Gitter when you comment on their issue/pull request, and of course link to it. For example: "Hey @dogi, just commented on your issue: https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/15"

**Comment by Chris-Boe** [comment]
@hannahgdubin , I completely agree. That will help keep the First Steps page from getting too long. I can add this change to the [First Steps Improvement Page](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/481) if that's alright with you and a couple other reviewers

**Pull request merged**
