### PR TITLE
Delete Manage Sync instruction in Planet Tutorial (fixes #2666)

### LINKED ISSUE #2666: Complete Manage Sync instructions for Step 4 - Planet Tutorial
### Problem
In Step 4 - Planet Tutorial, under **Different Kinds of Updates to Your Community** section, 
4. Finally, send an activities sync to the nation using `Manage Sync`.
Shouldn't we clarify whether to `Run Sync` or not as once the VI is in this step he gets confused whether to click on `Run Sync` or not? At least I was.    

### Steps to reproduce the problem

N/A

### Proposed solution

Either Delete step 4 as the same step is explained clearly in Step 7 - Nation Planet or 
Mention whether to click on `Run Sync` or not, for clarification.

### PR DESCRIPTION
**Pull request by 007HD**
Fixes # 2666

### Description
Delete Step 4 in "Different Kinds of Updates to your Community" section to reduce redundancy. The same step used again in Step 7 - Nation Planet 

### Raw.Githack preview link

https://raw.githack.com/007HD/007HD.github.io/hd-issue-2666/#!pages/vi/vi-planetapps.md

### CODE REVIEW

**Comment by 007HD** [comment]
@raisinman99 Thanks for the approval

**Comment by 007HD** [comment]
Made an additional commit to address this requirement: https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/2666#issuecomment-524079810

Instead of deleting Step 4, added instructions for `Run Sync` for further clarification.

**Comment by 007HD** [comment]
@perryc85 Thanks for the approval!

**Comment by perryc85** [comment]
You're welcome!

**Pull request merged**
