### PR TITLE
Fixed the typo number in feedback page #2. (Fixed #2616) 

### LINKED ISSUE #2616: Typo number on the feedback page
### Problem

Just a small typo on the feedback page (Giving feedback to different items section). Number 3 are duplicated. Let me know, If I can work on it. Thank

Just FYI

* I'm not sure why, If you look the issue using this link ( https://open-learning-exchange.github.io/#!./pages/manual/planet/feedback.md ), number 1 will be duplicated for all the steps. I have seen this many time in different pages but still can't figure out the reasons yet.

BUT

* If you look at the code on github (https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/master/pages/manual/planet/feedback.md), the number will listed correctly except the duplicated number 3.

### Steps to reproduce the problem

N/A

### Screenshots

Screenshot from 2019-08-03 19-10-12

### Proposed solution

Just change it to 4.

### PR DESCRIPTION
**Pull request by aasenomad**
Fixes #2616 

### Description
This is a new pull request. I closed the first one. Fixed the typo number, change 3 to 4.

### Raw.Githack preview link

As I stated on my issue, If you view the change using the raw.githack link (https://raw.githack.com/aasenomad/aasenomad-ole.github.io/typonumber/#!./pages/manual/planet/feedback.md) you will not able to see the change I make and you will see duplicated number 1 for all the list instead, I'm not sure the reasons but,

If you view on my github branch (https://github.com/aasenomad/aasenomad-ole.github.io/blob/typonumber/pages/manual/planet/feedback.md), everything is fine now. I already fixed it so you will not see duplicated number 3 anymore.

### CODE REVIEW

**Comment by aasenomad** [comment]
@lmmrssa: Please let me know if this is good. I deleted my GitHub repo and folk a new one but I still use the same naming for all the files.

**Comment by aasenomad** [comment]
@lillyxxx : This is the original OLE link 
( https://open-learning-exchange.github.io/#!./pages/manual/planet/feedback.md ). Please check if you see duplicated number 1s because I do. I'm not sure why it is not responding in browser according to the md file in Github. I clear my browser cache and history but still the same. I also open in incognito and privacy mode but still it duplicated

So the only way I can see the change is in Github, that's why I provided the GitHub page.

**Comment by lillyxxx** [comment]
@aasenomad There're some helpful links for Markdown provided in step3. You can check those links to get some idea. You can try to indent or try not to trigger an order list to set the number.

**Comment by aasenomad** [comment]
@lillyxxx: I understand what you saying, but I have absolutely no idea what you trying to imply. what I'm saying is I did not cause or make any changes that lead to duplicate the numbers and it has absolutely nothing to do with my PR. I just mention that on my PR because I saw some duplicated numbers on multiple pages but everytime I went to GitHub code to fix it, everything is fine and there are no duplicated numbers to fix. 

Going to step 3 is pointless for me right now because I believe that it happened to everyone and I have no idea how to fix it for all.

Have you checked this issue on your page? if you go your page( https://lillyxxx.github.io/lillyxxx-ole.github.io/#!./pages/manual/planet/feedback.md ) and under Giving Feedback To Different Items,  you will be noticed that it's also duplicated on your page too.

**Comment by lmmrssa** [comment]
@lillyxxx thanks for testing
@aasenomad I understand based on your issue it was just changing number **3** to **4** but currently your changes will not be reflected because there is some error on the page. And while we merge your PR it will still be showing 1 for all numbers. So it will good to see things are fixed, otherwise your PR will not reflect anything. That is what @lillyxxx seems to state in her comments.
@aasenomad Problem here should be indentation of content or spacing added. So can you try to fix that.

**Comment by aasenomad** [comment]
@lmmrssa: thanks for clarifying but I'm not sure what you mean by the problem is identation of content or spacing added. I didn't add any idention or spacing on the code, Like I said I just change 3 to 4 and that it. I also check again on the code but I didn't see any spacing are added on the line. If you can show me, it will be great so that I can fix it easily. Thanks

**Comment by aasenomad** [comment]
@lmmrssa Since I already have succussfully 5 PR requirement, I can closed this one for now if the team are currently trying to fix why it display all number 1s on the page. I can come back later and create this issue again or maybe some future intern can fix this. let me know.

**Comment by lmmrssa** [comment]
@aasenomad I understand you changed number in your PR. But issue or fixes should solve the problem. And markdown does not work with text that you put on page. It is about how it renders.
All numbers shows `1` because even when you put any other number as indentation are not properly set on first place it will never change to show up sequentially.
If you are not able to solve this issue then you can go can close this. But to note you do not have 5 PR. You should have 5 PR before you move to step 9. Adding yourself to team is not counted on it.

**Comment by aasenomad** [comment]
@lmmrssa : I understand about fixing not only my issue but I'm not very familiar with markdown so I was thinking it will be better if people with more knowledge than me fix this issue so that I don't cause another problem. 

Oh, I counted 5 approved PR on closed PR tabs but I guess I understand what you saying, right now I only see Number of Merge PRs : 4 in Tracking process page.

I'll close this one for now, and will create another issue.

Thank for the help.

**Pull request closed without merging**
