### PR TITLE
Adding drop downs

### LINKED ISSUE #2506: Adding drop-down feature to Git Repositories section
### Problem
The Git Repositories page has a lot of information that can be missed or skipped when you are going through the page. 

### Steps to reproduce the problem

N/A

### Screenshots

Screen Shot 2019-07-01 at 10 09 36 AM

**What the page would look like with the drop-down:**
Screen Shot 2019-07-01 at 10 09 36 AM

### Proposed solution

To make it more easy to read and not miss any of the details, I think adding a drop-down for each of the hyperlinks would make the page much cleaner and easier to follow.

### PR DESCRIPTION
**Pull request by hemu-codes**
Fixes #2506 

### Description
Because the Github Repositories page contains a lot of information, adding drop-downs would make it easier for users to navigate through the page. I have tried 2 different drop-down views (with the last section having a different view). I would still need to clean up a few more things on the page but do let me know if the drop-downs are useful and which version would be more useful/cleaner. 

### Raw.Githack preview link

https://raw.githack.com/hemu-codes/hemu-codes.github.io/adding-drop-downs/#!pages/vi/vi-github-and-repositories.md

### CODE REVIEW

**Comment by hemu-codes** [comment]
@lmmrssa After researching how to add drop-downs in Markdown, there was only two kinds of drop-down I could add: 1 with the details showing and the user can manually close it once they've seen and the other is shown in the following image:
Screen Shot 2019-07-15 at 11 31 30 PM

**Comment by ChiragAwale** [comment]
@lmmrssa @hemu-codes I think the first thing to do is, the drop-down-content should be shown first rather than be hidden when the page is first loaded. Also, you should consider putting the arrow right beside the heading.

**Comment by hemu-codes** [comment]
@ChiragAwale I've made some changes. Could you look over it again? The trouble I'm having with adding the drop-downs is that the hyperlinks to each of the section stop working after the dropdowns are added and another issue (a smaller one) is that I have to have the section title twice because I can't format the drop-down text.

**Comment by lmmrssa** [comment]
@hemu-codes with this changes, Link on Start here does not work. So lets not put it here.
Initial assumption was that you do not find content easily as points of Start here was not highlighted. But you are making other section highlighted.
i don't think we need expandable section on those part. It will just make it more hidden as someone might click it and then do not know it got collapsed so there is some content there.

**Pull request closed without merging**
