### PR TITLE
Update vi-first-steps.md fixes issue #1918

### LINKED ISSUE #1918: First Steps Markdown Big Picture put software and languages in a list
### Problem
When you read the third paragraph in the Big Picture section there are 13 software programs and languages listed in sentence form. This would seem to be a good place to use markdown lists to make this section easier to read. Possibly each of these in the list could be links to each main site describing the software and languages. 

### Steps to reproduce the problem

N/A

### Screenshots

issuetwo

### Proposed solution

Once accepted, you and your team will work on an assignment, and we’ll switch up the assignments each week. As part of this internship, you will have the opportunity to work with software and languages including:
  * [Git](https://en.wikipedia.org/wiki/Git) 
  * [GitHub](https://github.com/)
  * [Markdown](https://daringfireball.net/projects/markdown/syntax)
  * [Vagrant](https://www.vagrantup.com/)
  * [VirtualBox](https://www.virtualbox.org/)
  * [Command Line/Terminal](https://en.wikipedia.org/wiki/Command-line_interface)
  * [Command Line/Terminal Scripts](https://www.codecademy.com/articles/command-line-commands)
  * [Vim](https://www.vim.org/)
  * [CouchDB](http://couchdb.apache.org/)
  * [Docker](https://www.docker.com/)
  * [HTML5](https://html5demos.com/)
  * [JavaScript](https://www.javascript.com/)
  * [Node.js](https://nodejs.org/en/)
  * [Angular](https://angular.io/)

### PR DESCRIPTION
**Pull request by rkinback**
Fixes #1918

### Description
This is to help new interns easily access web pages to learn about the software tools and programming languages that they will be using during the internship.

### RawGit preview link

https://rawgit.com/rkinback/rkinback.github.io/new-i3/#!./pages/vi/vi-first-steps.md

### CODE REVIEW

**Comment by xyb994** [comment]
I think we should use either https://en.wikipedia.org/wiki/HTML5 or https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5 for HTML5
and
either https://en.wikipedia.org/wiki/JavaScript or https://developer.mozilla.org/en-US/docs/Web/JavaScript for Javascript.

**Comment by rkinback** [comment]
I changed the HTML5 and Javascript links. thanks

**Comment by aakarnik** [comment]
@rkinback How about using this [website](https://git-scm.com/) for Git - I thought it was easier to explore around than Wikipedia.

**Comment by rkinback** [comment]
@aakarnik  Yea that one does look better. I will change that now. thanks.

**Pull request merged**
