### PR TITLE
Improvement for githubissues.md (#743)

### PR DESCRIPTION
**Pull request by Yurockkk**
I add a short paragraph about deleting the branch that is associated with already-merged pull request. Here is the [rawgit](https://rawgit.com/Yurockkk/Yurockkk.github.io/newBranch3/#!./pages/githubissues.md)

### CODE REVIEW

**Comment by Yurockkk** [comment]
@mappuji I just updated the reduced image of deleteMergedBranch please take a look [here](https://rawgit.com/Yurockkk/Yurockkk.github.io/newBranch3/#./pages/githubissues.md)

**Comment by Yurockkk** [comment]
@mappuji Do you mean the file size of the image is too big or the dimension (width, height) of the image is too big? If it's the latter, I'll resize the dimension to 50% of the current width and height and push a new commit :smile:

**Comment by mappuji** [comment]
@Yurockkk I meant the dimension (width, height). Thank you.

**Comment by Yurockkk** [comment]
@mappuji Done! please take a look at [here](https://rawgit.com/Yurockkk/Yurockkk.github.io/newBranch3/#!./pages/githubissues.md)  :grin:

**Pull request merged**
