### PR TITLE
TeamViewer Setup Docs

### PR DESCRIPTION
**Pull request by bsocial**
Created teamview how to docs for TGs. 

[Why is my rawgit not working!!](https://rawgit.com/bsocial/bsocial.github.io/teaviewer/#!pages/vi/vi-teamviewer-install.md)

===
01/15/2018
https://rawgit.com/open-learning-exchange/open-learning-exchange.github.io/TeamViewer/#!pages/techgenius/tg-teamviewer-install.md

### CODE REVIEW

**Comment by amanuely** [comment]
@bsocial  I think your  rawgit is not working because of two things
1) there is a type in the branch name in the link- TeamViewer vs teaviewer
2) -teamviewer-install.md  file is in another folder, not in the pages/vi folder. 

https://rawgit.com/bsocial/bsocial.github.io/teaviewer/#!pages/vi/vi-teamviewer-install.md

**Comment by xyb994** [comment]
@bsocial right link here https://rawgit.com/open-learning-exchange/open-learning-exchange.github.io/TeamViewer/#!pages/techgenius/teamviewer-install.md

**Comment by kylemathias** [comment]
@bsocial I know i am late to comment, but you are making branches in the master OLE repository for a Wiki. Make your branches in your own forked repository and make the changes there.

**Comment by xyb994** [comment]
Maybe we should rename teamviewer-install.md to tg-teamviewer-install.md for consistency in the [folder](https://github.com/open-learning-exchange/open-learning-exchange.github.io/tree/master/pages/techgenius)?

**Pull request merged**
