### PR TITLE
Brief sentence recommending 5 pieces of markdown added (issue #911)

### PR DESCRIPTION
**Pull request by alexkarasik**
You can find it underneath the 2nd paragraph of the 'Create a new file as your personal MD Wiki page and commit your changes' heading
rawgit link:
https://rawgit.com/alexkarasik/alexkarasik.github.io/markdownrec/#!pages/githubandmarkdown.md
Issue link: #911 (forgot to initially include this)

### CODE REVIEW

**Comment by kylemathias** [comment]
#911 This is the open issue for this.

**Comment by alexkarasik** [comment]
What should I do to resolve this merge conflict?

**Comment by alexkarasik** [comment]
I apologize for the confusion. I think I have made all of the corrections properly.

**Comment by sarah-lu102** [comment]
I think it looks ok now

**Pull request merged**
