### PR TITLE
Docker guide

### PR DESCRIPTION
**Pull request by empeje**
This is work in progress, please not merge this one yet.

Here us the [RawGit Link of Docker Planet Wiki](https://cdn.rawgit.com/open-learning-exchange/open-learning-exchange.github.io/docker_guide/#!pages/robots/rbts-docker.md)

### CODE REVIEW

**Comment by xyb994** [comment]
@mappuji Can we consider merge this so contributors/VIs would know docker is another potential project?

**Comment by mappuji** [comment]
Sure, but I should finish add couple more contents.

**Comment by mappuji** [comment]
I think you can merge now @xyb994

**Comment by lmmrssa** [comment]
@mappuji @xyb994 is not here :) so we should approve and merge ourself. approving this PR

**Pull request merged**
