### PR TITLE
PR for resolving issue #930

### PR DESCRIPTION
**Pull request by navneetkarnam**
I have created this PR to resolve issue #930 
Here is the raw git link to the page:
[githubandmarkdown.md](https://rawgit.com/navneetkarnam/navneetkarnam.github.io/navneetkarnam-issue-930/#!pages/githubandmarkdown.md)

### CODE REVIEW

**Comment by sarah-lu102** [comment]
if the pdfs are too small to see, I would just remove them since the next link contains pretty much everything they need to know

**Comment by navneetkarnam** [comment]
@sarah-lu102  The images enlarge when you click on them! :)

**Comment by sarah-lu102** [comment]
I still cannot read the text when they are enlarged...

**Comment by navneetkarnam** [comment]
@kylemathias sure no problem, I'll work on that now!

**Comment by navneetkarnam** [comment]
Ill Close this PR for now and will create a new one with proper changes in order to avoid any confusions

**Pull request closed without merging**
