### PR TITLE
added estimated time to complete table for each step (fixes #3412)

### LINKED ISSUE #3412: No detailed overview of time to complete each step
### Please verify the following:

- [X] This issue is related to the [Virtual Interns First Steps](https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md) document or [Planet User Manual](https://open-learning-exchange.github.io/#!pages/manual/planet/overview.md).
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Avi) to avoid duplicates.

### URL to the MDwiki page containing the problem

https://open-learning-exchange.github.io/#!pages/vi/vi-first-steps.md

### Problem

There is no table or any overview of each step and time estimated to complete each step. 

### Screenshots (when necessary)

_No response_

### Proposed solution(s)

Making a table like this 
| Steps | Est. Time to Complete | 
|----------|----------|
| Step 0 | 1-2 hrs   | 
| Step 1   | 1 hr  |
| Step 2   | 2 hrs  |

This is just a rough idea, but it would be beneficial to add this under the FAQ section, so interns know where to prioritize and manage their time to complete each step.

### PR DESCRIPTION
**Pull request by Gavinp14**
**Important:** *Do not tick a checkbox if you haven’t performed its action.*

### Before Creating the Pull Request

- [x] Verify the changes are on a new branch other than `master` – it should say "compare: branch-name".
- [x] Start the pull request title with lowercase letters, e.g., `add githubusername.md`.
- [x] Add issue number to the end of the pull request title when applicable, e.g., `update mi-faq.md (fixes #3264)`.

### After Creating the Pull Request

- [x] Go to "Commits" tab, make sure the commit username is clickable and linked to your GitHub account correctly.
- [x] Review the "Files changed" tab to ensure there are no unnecessary files or changes included in the pull request.
- [x] Verify that the raw.githack preview link is included in the description.
  - [x] Preview the MDwiki rendered changes using the raw.githack link. Ensure it displays as expected without any errors.
- [x] Drop a link to this pull request in our discord channel.

### Description, Screenshots and/or Screencast
timeTable

fixes #3412 

### Raw.Githack Preview Link
https://raw.githack.com/Gavinp14/Gavinp14.github.io/3412-estimated-time-table/index.html#!pages/vi/vi-first-steps.md

### CODE REVIEW

**Comment by xyb994** [comment]
I'll need to marinate on this a little bit.

I feel this change would make this page even longer. It's not bad to have an overview, but perhaps use a list (kinda ugly as not as easy to see) instead of table since we don't get to customize MDwiki's table rendering? Or perhaps a screenshot of the table in excel/google form so it takes up less space? Alternative we could also just integrate the amount of time it takes for each step into the short description in each step on the first steps page, on top of linking to FAQ with the table?

**Comment by Gavinp14** [comment]
What if we just put a link to a jpeg or png of the time estimation table instead of embedding it on the page? That way it won't take up any space and if people want to view it, they can have it on its own separate tab.

**Comment by xyb994** [comment]
Screenshot 2024-10-14 at 12 13 08 PM

While putting a screenshot there simplifies the problem, I think it might be a good idea to still be able to jump to the step with a click, so I was experimenting with a few different options with a list, what do you think? I like the last one more

**Comment by Gavinp14** [comment]
> Screenshot 2024-10-14 at 12 13 08 PM
> While putting a screenshot there simplifies the problem, I think it might be a good idea to still be able to jump to the step with a click. I was experimenting with a few different options with a list, what do you think? I like the last one more
> 
> I also moved the time estimation from everybody to a [google sheet](https://docs.google.com/spreadsheets/d/1SuaiOyYFoXPSEoxw1jD-XpVIWTTKoEr5TbU0rfrkk10/edit?usp=sharing). Could you update the time for each step with what's in column j?

I think this concept works great! It gives interns knowledge as to how long it will take to complete each step without taking up lots of space

**Comment by xyb994** [comment]
Closing this as #3427 seems to sufficiently provide the time context

**Pull request closed without merging**
