### PR TITLE
Change git-related links to subcategories (fixes #1691)

### LINKED ISSUE #1691: FAQ git/github link collection changes
I have a few suggested changes for the git/github/markdown links section in the FAQ
http://open-learning-exchange.github.io/#!pages/vi/vi-faq.md. This will be a bit lengthy.

i) I am missing my all-time favorite git-resource: http://gitimmersion.com/
It gives a bit more depth than most beginner tutorials, but also not too much (covers aliases, common shortcuts, setting up a .bashrc file with non-standard git log output that can be copied, etc.). Still only about an hour commitment or so.

ii) This list is getting quite long, so it is not clear which one to start with.
I would suggest breaking it down into subcategories. I will give a suggested breakdown in a comment below for discussion. May take a few iterations to get something good for this kind of change.

iii) Breaking out Vi/Vim, since not strictly related IMHO. Would not be obvious where to find it if I was looking for it.

iv) Maybe add some reading on common git workflows? It helped me a lot when I got started with git. That could maybe be the case for others as well? 

iv) It was a long time since I looked at the Codecademy course, but from my recollection I found it to be a bit time consuming for the amount of info I was able to internalize. Anyone else have other experience from that course?

### PR DESCRIPTION
**Pull request by Tille88**
https://rawgit.com/Tille88/Tille88.github.io/5ae329c/#!pages/vi/vi-faq.md

Please feel free to give suggestions of different categorizations if you have better way to organize the links

### CODE REVIEW

**Comment by xyb994** [comment]
@Tille88 

Looks like indentation become tabs instead of spaces starting at [line 160](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1693/files#diff-127db802c803eb3f3e8824408bc360b9R160).

`#####` doesn't seem to do anything at [line 154](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1693/files#diff-127db802c803eb3f3e8824408bc360b9R154), [159](https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1693/files#diff-127db802c803eb3f3e8824408bc360b9R159), etc. Also there are two spaces between  `#####` and text.

**Comment by Going-Gone** [comment]
I think it looks good, but I think questions and answers could do without the  "Q''s before the number of each.

**Comment by Tille88** [comment]
@xyb994 https://rawgit.com/Tille88/Tille88.github.io/84a9b5d/#!pages/vi/vi-faq.md
Changed tabs to 4 spaces, removed ###### (did make it in bold before, but this is perhaps cleaner), and double space issue

**Comment by Tille88** [comment]
@Going-Gone Thank you for the comment. 
I think it would be a bit of scope creep to have discussion about that here, which ppl may agree or disagree with, so maybe would require new issue, or leaving sth for future interns to pick up and run with :)

**Comment by Tille88** [comment]
@xyb994 I see what you meant, #*5 only did that in the markdown viewer, not the actual page. Thank you for pointing that out

**Comment by Jackbui96** [comment]
Everything looks cleaner and more organize now. Thank you Tille88.

**Pull request merged**
