### PR TITLE
Update GitHub issues page (Fixes #2563)

### LINKED ISSUE #2563: Minor Change in Github Issues page
### Problem
Although this is a minor change, in the Github Issues page, where it explains how you create a new branch, it doesn't emphasize that we have to create a new branch for any new issue we create. 

### Steps to reproduce the problem

N/A

### Screenshots

Screen Shot 2019-07-17 at 10 35 15 PM

### Proposed solution

Bolding this sentence will make the interns understand the significance/importance of creating a new branch for each issue.

### PR DESCRIPTION
**Pull request by hemu-codes**
Fixes #2563 

### Description
In the Github Issues page, where it explains how you create a new branch, it doesn't emphasize that we have to create a new branch for any new issue we create. The solution was to bold the sentence to emphasize its importance. 

### Raw.Githack preview link

https://raw.githack.com/hemu-codes/hemu-codes.github.io/update-github-issues-page/#!pages/vi/vi-github-issues.md

### CODE REVIEW

**Comment by perryc85** [comment]
Hey there, I'd recommend adding the issue your pull request fixes to its title. For example: Update GitHub issues page (Fixes #2563)

**Comment by hemu-codes** [comment]
@perryc85 Just fixed it! Thanks for the feedback :)

**Comment by perryc85** [comment]
You're welcome.

**Comment by hemu-codes** [comment]
@lmmrssa I just resolved the conflict on the PR but I'm not sure why an image is being added to each of the branches. Is there any way I could remove these images from the different branches? Thanks again for all the help!

**Pull request merged**
