### PR TITLE
yaoxing1990.md profile

### PR DESCRIPTION
**Pull request by yaoxing1990**
https://github.com/yaoxing1990/yaoxing1990.github.io/blob/xing-new-branch/pages/profiles/yaoxing1990.md

### CODE REVIEW

**Comment by yaoxing1990** [comment]
Updated profile and added to correct folder

**Comment by xyb994** [comment]
http://rawgit.com/yaoxing1990/yaoxing1990.github.io/xing-new-branch/index.html#!./pages/vi/profiles/yaoxing1990.md

@yaoxing1990 MDwiki's rendering is a bit different from GitHub, you might want to add some empty lines to make it looks the same as GitHub's preview.

**Comment by yaoxing1990** [comment]
@kylemathias https://github.com/yaoxing1990/yaoxing1990.github.io/blob/xing-new-branch/pages/vi/profiles/yaoxing1990.md

Here is the new link

**Comment by yaoxing1990** [comment]
@xyb994 So is there a template of Github preview rendering?

**Comment by xyb994** [comment]
@yaoxing1990 I'm not sure what you mean by "template of Github preview rendering". Github's rendering of Markdown is like [the link you posted above](https://github.com/yaoxing1990/yaoxing1990.github.io/blob/xing-new-branch/pages/vi/profiles/yaoxing1990.md) or what you see in the "Preview" tab when you are editing a markdown document on GitHub's web interface.

What I meant in my previous comment is that [MDwiki's version](http://rawgit.com/yaoxing1990/yaoxing1990.github.io/xing-new-branch/index.html#!./pages/vi/profiles/yaoxing1990.md) and [GitHub Flavored version](https://github.com/yaoxing1990/yaoxing1990.github.io/blob/xing-new-branch/pages/vi/profiles/yaoxing1990.md) of `yaoxing1990.md` looks different and the latter one might be the one you want your profile to look like. In order to make the previous one look identical to the latter one, you might need to add some empty lines between certain Markdown elements.

**Pull request merged**
