### PR TITLE
New Pull

### PR DESCRIPTION
**Pull request by benjammin12**
Added more information about my hobbies and my programming experience.

### CODE REVIEW

**Comment by dogi** [comment]
Hmm - this is creating merge conflicts

@benjammin12 please resolve the conflct or close this pull request

**Comment by benjammin12** [comment]
Any idea why that happened dogi?

**Comment by benjammin12** [comment]
@dogi

**Comment by dogi** [comment]
yes

you did `git pull origin/master`
and then git complained about merge conflict
which was exactly this what we saw
```
<<<<< head
...
-------
...
>>>>>
```
and wanted you to resolve that manually ;)
you did not read anything about that complain
and just added the changes to your local repo
with `git add ...` and git commit -m '...'`
then with `git push` you pushed it to github,
where you created a pull request ...

long story short - try reading some of the git messages sometimes it helps
also use
`git diff`
and
`git status`

**Pull request closed without merging**
