### PR TITLE
Issue #857 -Summary for Git Repositories page

### PR DESCRIPTION
**Pull request by alexkarasik**
Here is a link to the issue: #857 (I suggested adding a step-by-step summary to the end of pages with instructions)

For some reason, the link did not work and returned a 404 error. Here is the link to copy and paste in a new tab: https://rawgit.com/alexkarasik/alexkarasik.github.io/step-by-step/#!pages/gitandrepositories.md

[x] Summarized the main objectives of the page 
[x] Wrote out all command lines again in order of execution
[ ] If this was done properly, do the same for the other Git Pages
[ ] Figure out how to get those darn bullet points to show properly

### CODE REVIEW

**Comment by sarah-lu102** [comment]
there are 21 files changed- I think you might have merged others' changes into your branch and then tried to PR that branch. I think it would be easiest to update your master branch with the upstream, then create a new branch and copy the edits you made to the file that you want to change (don't merge the branch with anything, only make your changes). Then you can do a PR with that branch. I made the same mistake when I was going through the steps as well 😄

**Comment by alexkarasik** [comment]
Thanks Sarah, I think I've done it correctly, so I will make a new pull request now with the new branch.

**Comment by alexkarasik** [comment]
I wrote out 'git fetch upstream master', 'git checkout master and then 'git merge upstream/master'. Then, I checked out a new branch and just copied and pasted my additions into the file and added committed these changes and pushed them. I see when I look at the pull request that all of the same commits are still showing up. I am not sure what I am still doing wrong.

**Comment by sarah-lu102** [comment]
did you do git push after doing git merge?

**Comment by alexkarasik** [comment]
Yes, I did 'git push origin master' after 'git merge upstream/master' and I still got all of those commits coming up...

**Comment by sarah-lu102** [comment]
hmm... I'm not sure either. Message the gitter chat (@snazzybunny or @paulbert  or @kylemathias)

**Comment by alexkarasik** [comment]
ok, thanks

**Pull request closed without merging**
