### PR TITLE
Added sign in and member section on myPlanet  (fixes #3552).

### PR DESCRIPTION
**Pull request by deeppp15**
### Description
- Added a single line description on myPlanet overview page on manual. To make it consistent with planet manual.
- Added a new md page which has steps and screenshots assigned for becoming a member and logging in.

### Fixes
fixes #3552

### Raw.Githack Preview Link
- Modified Page- https://raw.githack.com/deeppp15/deeppp15-ole.github.io/3552-myPlanet-signIn-population/index.html#!pages/manual/myplanet/overview.md
- Added Page-  https://raw.githack.com/deeppp15/deeppp15-ole.github.io/3552-myPlanet-signIn-population/index.html#!./pages/manual/myplanet/myPlanetMember.md

### CODE REVIEW

**Review by xyb994 — APPROVED** [review]

**Comment by xyb994** [comment]
Content looks all good.

Could you follow similar naming pattern for all added images and markdown files as in planet manual folder? Some example:
- rename `pages/manual/myplanet/myPlanetMember.md` to `pages/manual/myplanet/myplanet-member.md`
- rename `pages/manual/myplanet/images/SignIn Page.jpg` to `pages/manual/myplanet/images/signin-page.jpg`
- rename `pages/manual/myplanet/images/existingUsers.jpg` to `pages/manual/myplanet/images/signin-existing-users.jpg`
- ...

**Comment by deeppp15** [comment]
> Content looks all good.
> 
> Could you follow similar naming pattern for all added images and markdown files as in planet manual folder? Some example:
> 
> * rename `pages/manual/myplanet/myPlanetMember.md` to `pages/manual/myplanet/myplanet-member.md`
> * rename `pages/manual/myplanet/images/SignIn Page.jpg` to `pages/manual/myplanet/images/signin-page.jpg`
> * rename `pages/manual/myplanet/images/existingUsers.jpg` to `pages/manual/myplanet/images/signin-existing-users.jpg`
> * ...

Sure on it !

**Comment by xyb994** [comment]
@deeppp15 I made some changes to text here on github.com. Don't forget to run `git pull` to fetch the changes before you renaming them.

**Comment by deeppp15** [comment]
> @deeppp15 I made some changes to text here on github.com. Don't forget to run `git pull` to fetch the changes before you renaming them.

Yes Yibo, pulled recent changes, changing filenames now

**Comment by deeppp15** [comment]
Hi Yibo, updated the files according to the suggestions

**Comment by xyb994** [comment]
Since the folder stores all images for the myplanet manual, could you please prefix the image names with `signin-` to make it easier to identify which page those images belong to in the future?

**Comment by deeppp15** [comment]
> Since the folder stores all images for the myplanet manual, could you please prefix the image names with `signin-` to make it easier to identify which page those images belong to in the future?

Sure or should I make a sign in folder ?

**Comment by xyb994** [comment]
> > Since the folder stores all images for the myplanet manual, could you please prefix the image names with `signin-` to make it easier to identify which page those images belong to in the future?
> 
> Sure or should I make a sign in folder ?

Let's just follow the existing structure and not create another sub-folder.

**Review by xyb994 — APPROVED** [review]

**Pull request merged**
