### PR TITLE
Adding profile to vi-team

### PR DESCRIPTION
**Pull request by SAI-JAHNAVI**
### Description
Adding my profile to the virtual intern list

### Raw.Githack preview link

https://raw.githack.com/SAI-JAHNAVI/SAI-JAHNAVI.github.io/addTo/vi-team/#!pages/vi/vi-team.md

### CODE REVIEW

**Comment by lmmrssa** [comment]
@SAI-JAHNAVI where you have profile file here?

**Comment by lmmrssa** [comment]
sorry i was asking why you have profile file on PR for adding in team

**Comment by SAI-JAHNAVI** [comment]
@lmmrssa Let me explain clearly what I did here, 

As mentioned in step 9, I added my self to the virtual intern list in vi-team.md 
Capture

Screenshot (102)_LI

Capture

You can check this in https://raw.githack.com/SAI-JAHNAVI/SAI-JAHNAVI.github.io/addTo/vi-team/#!pages/vi/vi-team.md

To add name in virtual intern list I created saijahnavivaka.md in profiles folder to add the link (profiles/saijahnavivaka.md) as in above pic {just like how other profiles are added}. So you are seeing 2 changed files here
1. pages/vi/vi-team.md
2. pages/vi/profiles/saijahnavivaka.md

Please let me know where I went wrong and what are the changes I need to make. Thankyou!

**Comment by SAI-JAHNAVI** [comment]
@lmmrssa I removed the profile file. Now we have only the changes related to PR here. Thankyou!

**Comment by singharpita** [comment]
Old PR.

**Pull request closed without merging**
