### PR TITLE
Pull request that adds article link on virtualization issue #389

### PR DESCRIPTION
**Pull request by IshanSoni**

### CODE REVIEW

**Comment by IshanSoni** [comment]
@aberdean I had to add a <br /> tag otherwise the next link appeared on the same line as the link to enable virtualization.

**Comment by aberdean** [comment]
@IshanSoni http://stackoverflow.com/questions/22385334/how-to-write-one-new-line-in-bitbucket-markdown

**Comment by IshanSoni** [comment]
@aberdean ah thanks I am still treating markdown like HTML!

**Comment by IshanSoni** [comment]
@aberdean fixed

**Pull request merged**
