### PR TITLE
Updated name to vi-team.md

### PR DESCRIPTION
**Pull request by simily00**
Fixes #

### Description
I added my name to the vi-team.md intern list.

### RawGit preview link
https://rawgit.com/simily00/SimilyHill.github.io/add-my-name/#!pages/vi/vi-team.md

### CODE REVIEW

**Comment by simily00** [comment]
@Immrssa Yes, I don’t know where those changes came from, I am confused by that. I will redo it.

**Comment by simily00** [comment]
My master somehow has a submodule, so it keeps adding other stuff make a PR. I can’t seem to figure out how to undo this.

**Comment by simily00** [comment]
I still am having trouble with this, do you have any suggestions for me to try?

**Comment by lmmrssa** [comment]
@simily00 looks like you broke your fork repository. Simple fix is to remove the repository and fork it again. Other solution might be little difficult to follow.

**Pull request closed without merging**
