### PR TITLE
Update Collections instructions on Library & Resources Overview (fixes #2927) 

### LINKED ISSUE #2927: Add collections screenshots out of date
### Problem
The screenshots used to show how to add a collection do not match the UI on the manager account.

### Steps to reproduce the problem
1. Login as a manager and go to the library page.
2. In a separate window, go to https://open-learning-exchange.github.io/#!pages/techgenius/tg-library-management.md and scroll to "How do I create and use collections?"
3. Compare the screenshot examples to the UI (see below)
4. Select "collections" and compare the screenshot examples to the UI (see below)
5. Select "create new collection" and compare the screenshot examples to the UI (see below)

### Screenshots
####First comparison:
Actual:
Screen Shot 2020-04-15 at 5 02 16 PM
vs.
Example:
Screen Shot 2020-04-15 at 4 59 21 PM

####Second comparison:
Actual:
Screen Shot 2020-04-15 at 5 02 28 PM

vs.
Example:
Screen Shot 2020-04-15 at 4 59 33 PM

####Third comparison:
Actual:
Screen Shot 2020-04-15 at 5 02 49 PM
vs.
Example:
Screen Shot 2020-04-15 at 4 59 33 PM

### Proposed solution
Update screenshots, adjust directions to match.

### LINKED ISSUE #3050: Out of date instructions on Library and Resources Overview
### Problem
The instructions for the **How do I create and use Collections?** section on the **Library and Resources Overview** page are out of date. The screenshots and numbering are off, too. This is similar to issue #3035.

### Steps to reproduce the problem
Click on **Tech Geniuses** tab -> Choose **Content & Library Management** -> Click on **How do I create and use Collections?** on the left sidebar.

### Screenshots
Screen Shot 2020-05-16 at 10 26 46 AM
Screen Shot 2020-05-16 at 10 27 04 AM

### Proposed solution
Edit the instructions to reflect the current version and update the screenshots as follows:
Screen Shot 2020-05-14 at 2 04 06 PM
Screen Shot 2020-05-14 at 2 05 16 PM
Screen Shot 2020-05-16 at 9 53 26 AM

### PR DESCRIPTION
**Pull request by anthonyhvo12**
Fixes #2927  

### Description
Update instructions under the **How do I create and use Collections?** section on the **Library & Resources Overview** page.

### Raw.Githack preview link
https://raw.githack.com/anthonyhvo12/anthonyhvo12.github.io/library-manual-collections-2/#!pages/techgenius/tg-library-management.md

### CODE REVIEW

**Comment by anthonyhvo12** [comment]
@Mutugiii Good catch! PR #3029 has resolved that issue, though.

**Comment by Mutugiii** [comment]
@anthonyhvo12 Thanks for that clarification!

**Comment by anthonyhvo12** [comment]
@lmmrssa Thanks for your feedback. Should I create a completely new branch independent of #3051 and work on that, or should I make changes to the image names as you mentioned on this branch and add a note that it depends on #3051 to work? On a side note, I have made the requested changes on #3051.

**Comment by lmmrssa** [comment]
@anthonyhvo12 you made branch out of branch and which means its not just depended but once this is merged other branch changes will also go along. So you should always create new branch from master

**Comment by anthonyhvo12** [comment]
@lmmrssa That makes sense - I will do so.

**Comment by anthonyhvo12** [comment]
This PR has been replaced with #3086 to detach it from #3051 .

**Pull request closed without merging**
