### PR TITLE
fixed typo for issue #2967

### PR DESCRIPTION
**Pull request by chtelmko**
Fixes # 2967

### Description
Changed the word Rasperry to Raspberry to correct the typo.

### Raw.Githack preview link
https://raw.githack.com/chtelmko/chtelmko.github.io/TypoQSM/#!pages/techgenius/tg-hardware-setup.md

### CODE REVIEW

**Comment by chtelmko** [comment]
Thank you. What do I need to do to fix it.

**Comment by lmmrssa** [comment]
@chtelmko if you follow github part of 10 steps there is instruction on how to configure your local github copy

**Comment by chtelmko** [comment]
I followed step 5 of first steps: https://open-learning-exchange.github.io/#!./pages/vi/vi-github-and-repositories.md

It says the same thing as before(not sure where I am going wrong):

Windows_PowerShell printout

**Comment by chtelmko** [comment]
I have cloned the repository and went through all of step 5 steps again. Hope that has fixed the issue.

**Comment by lmmrssa** [comment]
@chtelmko your commit does not reflect to your account. check step 3 first part of login

**Pull request closed without merging**
