### PR TITLE
Router Configuration Guide (fixes #1251)

### LINKED ISSUE #1251: Pull Request Router Configuration Guide #1250
How to guide to assign static IP to community and configure network devices. 

https://raw.githubusercontent.com/open-learning-exchange/open-learning-exchange.github.io/routerconfig/pages/routerconfig.md

### PR DESCRIPTION
**Pull request by bsocial**
This is a how to for Tech Geniuses and others. Covers assigning static IP to Community and configuring network devices. I expect that there are typos...

### CODE REVIEW

**Comment by dogi** [comment]
https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues/1251

**Comment by dogi** [comment]
https://raw.githubusercontent.com/open-learning-exchange/open-learning-exchange.github.io/routerconfig/pages/routerconfig.md

**Comment by dogi** [comment]
https://rawgit.com/open-learning-exchange/open-learning-exchange.github.io/routerconfig/#!pages/routerconfig.md

**Comment by dogi** [comment]
@bsocial found it it is `pages/uploads/images/router-dhcp-reservation.png`
and
think it is the picture of this line 
`Click on “Address Reservation” and then “Add New”.`

**Comment by bsocial** [comment]
I fixed the image issue.

**Pull request merged**
