### PR TITLE
prompting user to add themselves to virtual intern list 

### PR DESCRIPTION
**Pull request by hannahgdubin**
This will resolve issue #409 Added to last step in firststep.md to prompt user to add themselves to the intern page I added this "After your survey is summited, please add yourself to the virtual intern list found in team.md and create a pull request."

### CODE REVIEW

**Comment by dogi** [comment]
@hannahgdubin I am no native english speaker so I can't help you as much as I would like too, but your tricky ;) way of putting your change between two steps involving survey is going against my logical instincts of not splitting up two related step ...

or  

in other words as much as I like the sentence starting with `Lately` there is a no lately in town :P 

please fix this

**Comment by hannahgdubin** [comment]
How does this sound @dogi  "Let us know in the Gitter chat when you're done, so we can send the survey to your community. Then, fill out the survey and submit it. Next, Sync your community with the nation (as you did in step 7). Lastly, once you have completed all other steps,  please add yourself to the virtual intern list found in team.md and create a pull request."

**Comment by dogi** [comment]
@hannahgdubin already much better from the flow of tasks ;)

**Comment by hannahgdubin** [comment]
@dogi great! I'll edit

**Pull request merged**
