### PR TITLE
create zhekaijin_scott.md

### PR DESCRIPTION
**Pull request by ZhekaiJin**
https://cdn.rawgit.com/ZhekaiJin/zhekaijin.github.io/mdtest/#!pages/vi/profiles/zhekaijin_scott.md

### CODE REVIEW

**Comment by xyb994** [comment]
@ZhekaiJin GitHub link at the last line is broken, other than that looks good :)

**Comment by ArashDai** [comment]
@ZhekaiJin  Your Rawgit link should look like this: https://cdn.rawgit.com/ZhekaiJin/zhekaijin.github.io/mdtest/#!pages/vi/profiles/zhekaijin_scott.md
Notice the #! before pages, it allows us to view markdown as it will look online.
Other than that I could make minor editing suggestions such as the capitalization on "If you want to know more about me:", and I would add an "s" to the end of "previous projects", also is "something about myself" filler text you intended to replace?

**Comment by ZhekaiJin** [comment]
Thanks for the great comment @ArashDai . I did want to add another style on "something about myself". and ":star: " ":basketball:" could not be rendered correctly on MDwiki in the rawgit link and I am not sure if it is fine that way.

**Comment by xyb994** [comment]
@ZhekaiJin MDwiki members page is where people look for your profile. This step is to make sure you are familiar with Markdown, it's up to you to change it or not.

**Comment by joeadom** [comment]
Please remove me from this thread, i'm not interested

**Pull request merged**
