### PR TITLE
Added 4 profiles

### PR DESCRIPTION
**Pull request by lorugant**
Please review this fix for #1352 Thanks!!

### CODE REVIEW

**Comment by dogi** [comment]
can you please add the rawgit link?

@lorugant also note that only one of this profiles you suggest was done by a later virtual intern ...

**Comment by lorugant** [comment]
Ok. Will change it to rawgit links.

**Comment by dogi** [comment]
3 files of https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1354 too much

**Comment by lorugant** [comment]
rawgit link: https://rawgit.com/lorugant/lorugant.github.io/Obranch/#pages/vi/vi-github-and-markdown.md

**Pull request closed without merging**
