### PR TITLE
Introduction of Vagrant command in vagrantwin.md

### PR DESCRIPTION
**Pull request by fangninghe**
I made some changes to the introduction of Vagrant Commands, please review.

### CODE REVIEW

**Comment by fangninghe** [comment]
Hi @hikaruit15, thanks for the comment. The reason why I listed all the options is that the new interns might open one of those options by chance, just like me did at the first place. I was stuck for a little while since I was so familiar with cmd commands. So I thought maybe other interns might meet the same problem and I listed all the possible solutions just in case. Moreover, I mentioned the best solution as well at the end of of the explanation.

**Comment by hikaruit15** [comment]
Hi @fangninghe,
Just my suggestion. 
By the way you were stuck because you followed the guide and the guide write about ** Command Prompt ** but doesn't show regular or admin. 
That's why I don't think new interns could open one of these options by chance (they are totally different) if we specify clearly the option. ( as you mentioned using ** git bash **)

**Comment by FanisGk** [comment]
I like your ideas @fangninghe. 
I can't find anything to add apart from @dogi's suggestion about the image.
Good job!

**Comment by fangninghe** [comment]
Hey guys, @hikaruit15, @waryhermit, @FanisGk , @dogi , so what should I change now? I am a little confused, on one hand I really learned something in studying the three methods, I hope other interns like me can obtain those information. On the other hand, I also want to keep the tutorial easy, short and clean, too long passage is kind of annoying. So offer me a common conclusion please, I appreciate it a lot.

**Comment by dogi** [comment]
sorry @fangninghe - I used this `pull request` as an example for all the `reviewers` we have ...

and as we know 4 people 4 opinons ;) anyhow I think if you add the picture to the repository and fix that link accordantly you PR is a go

**Pull request merged**
