### PR TITLE
Add chiragawale profile

### PR DESCRIPTION
**Pull request by ChiragAwale**
here is the preview link: 

https://github.com/ChiragAwale/chiragawale-ole.github.io/blob/add-chiragawale-profile/pages/vi/chiragawale.md

### CODE REVIEW

**Comment by YuserahN** [comment]
The githack link you provide must be of the following format: 

```https://raw.githack.com/username/username.github.io/branchname/#!./pages/vi/profiles/username.md```

**Comment by ChiragAwale** [comment]
I am sorry about the error, I have committed the Markdown and the here is the updated link. https://rawcdn.githack.com/ChiragAwale/chiragawale-ole.github.io/296a5da704d82d7cbfc15ce865606c31fdce2aea/pages/vi/chiragawale.md

**Comment by ChiragAwale** [comment]
I am sorry about the error, I have committed the Markdown and the here is the updated link. https://rawcdn.githack.com/ChiragAwale/chiragawale-ole.github.io/296a5da704d82d7cbfc15ce865606c31fdce2aea/pages/vi/chiragawale.md

**Comment by lmmrssa** [comment]
@ChiragAwale it would be nice if you can add some more markdown tags.

**Pull request merged**
