### PR TITLE
Removing old interns for Issue #432

### PR DESCRIPTION
**Pull request by kylemathias**
I went through all the pages and removed all interns that had 6 month or older pages and were not on the Members page: http://open-learning-exchange.github.io/#!pages/team.md . This should solve issue #432 .

### CODE REVIEW

**Comment by kylemathias** [comment]
I just read in #432 to not do more than 2. =(

**Comment by kylemathias** [comment]
I wanted to solve the issue completely, let me know if you would like me to close this out and only do 2.

**Comment by waryhermit** [comment]
@kylemathias Keep this pull request open so @dogi can decide - in the mean time make another branch and pull request with only 2 deleted and I can approve that right away.

**Comment by dogi** [comment]
@kylemathias and @waryhermit thanks

**Pull request closed without merging**
