### PR TITLE
increased readability (fixes #2809)

### LINKED ISSUE #2809: Less Readability on steps
### Problem
When the user clicks on any steps. The title doesn't appear with the current step no but only with the step name which makes confusion when multiple tabs are open. The user needs to scroll all way down to know which step he is in.

### Steps to reproduce the problem
N/A

### Screenshots
Screen Shot 2019-10-24 at 2 47 27 AM

### Proposed solution
Put the step number along with the title of the tutorial.

### PR DESCRIPTION
**Pull request by gyawaliamit7**
Fixes #2809 
Here is the link for the fix.
The concern was showing the steps number in tab bar as well for the easiness of the user.
https://raw.githack.com/gyawaliamit7/gyawaliamit7-ole.github.io/readability-issue/#!pages/vi/vi-nation.md

https://raw.githack.com/gyawaliamit7/gyawaliamit7-ole.github.io/readability-issue/#!pages/vi/vi-github-issues.md

### CODE REVIEW

**Comment by ChiragAwale** [comment]
Do put your raw git hack link on the fix

**Comment by lmmrssa** [comment]
@gyawaliamit7 your local git has not bee configured correctly. Please check https://open-learning-exchange.github.io/#!pages/vi/vi-github-and-markdown.md . There is link which explains how to have global configuration setting for github

**Comment by gyawaliamit7** [comment]
> Please put your raw git hack link on the fix
Here is the link for the fix
https://raw.githack.com/gyawaliamit7/gyawaliamit7-ole.github.io/readability-issue/#!pages/vi/vi-nation.md

**Comment by gyawaliamit7** [comment]
> @gyawaliamit7 your local git has not bee configured correctly. Please check https://open-learning-exchange.github.io/#!pages/vi/vi-github-and-markdown.md . There is link which explains how to have global configuration setting for github

**Pull request closed without merging**
