### PR TITLE
Added branching information to the github issues step (#360)

### PR DESCRIPTION
**Pull request by waryhermit**
I have made the changes @aberdean suggested, hopefully its clear enough.

### CODE REVIEW

**Comment by dogi** [comment]
@waryhermit the PR looks great

but want more eyes on this change
@aberdean @FanisGk @mepda @prmurphy and @hikaruit15 please add your comments

**Comment by aberdean** [comment]
@waryhermit This pull request is awesome! Thank you!

**Comment by FanisGk** [comment]
I also like your pull request @waryhermit! Good job!

**Comment by waryhermit** [comment]
@aberdean I see your change fixed the space in the link but now rawgit part isn't bold anymore. Its not very important, but I couldn't get it to look the way I wanted with just MD elements. I could using <tt> and <b> but it seems like there should be a way using just MD.

**Comment by aberdean** [comment]
@waryhermit I'd avoid using `<tt>`, but I think in this case we may want to use `<code>` and `<b>`.

In general, I'd be against mixing html and Markdown, but this seems to be one of those cases in which the benefit outweighs the cost! ;-)

**Comment by waryhermit** [comment]
@aberdean Ok, I used those tags.

**Pull request merged**
