### PR TITLE
add mi-github-pull-request.md (fixes #3326)

### LINKED ISSUE #3326: mi-github-and-markdown & mi-github-issues: redundant instructions
### Please verify the following:

- [X] This issue is related to the [Mobile Interns First Steps](https://open-learning-exchange.github.io/#!pages/mi/mi-10-steps.md) document.
- [X] You have searched for relevant keywords in [recent open and closed issues](https://github.com/open-learning-exchange/open-learning-exchange.github.io/issues?q=is%3Aissue+label%3Ami) to avoid duplicates.

### URL to the MDwiki page containing the problem

Provided below

### Problem

The **Open/Create Pull Request** and **Delete Branch** sections in Step 1 ([Markdown & Forking Workflow](https://open-learning-exchange.github.io/#!./pages/mi/mi-github-and-markdown.md)) 
and Step 6 ([GitHub Issues Tutorial](https://open-learning-exchange.github.io/#!./pages/mi/mi-github-issues.md)) present the same instructions, yet Step 6 has more content and details.  For example,

### Open Pull Request

The screenshot in Step 6 has the pull request template shown while the one in Step 1 doesn't have it, yet I found that template when I was creating a pull request in Step 1, which left me thinking whether I was on the right step or not. 

### Delete Branch

This section in Step 6 has the content displayed in Step 1 with some content added to it. 

### Screenshots (when necessary)

This is the Image provided in the **Open Pull Request** Section in Step 1

image

This is the Image provided in the **Open Pull Request** Section in Step 6

image

This is the **Delete Branch** section in Step 1

image

This is the **Delete Branch** Section in Step 6

image

### Proposed solution(s)

- Combining Both **Create Pull Request** and **Delete Branch** sections into one section for each that has the same general content and providing the link for it in both Steps 1 and 6.  
- Putting any additional content based on each step right after the link.

### PR DESCRIPTION
**Pull request by AdhamElAsfar99**
**Important:** *Do not tick a checkbox if you haven’t performed its action.*

### Before Creating the Pull Request

- [x] Verify the changes are on a new branch other than `master` – it should say "compare: branch-name".
- [x] Start the pull request title with lowercase letters, e.g., `add githubusername.md`.
- [x] Add issue number to the end of the pull request title when applicable, e.g., `update mi-faq.md (fixes #3264)`.

### After Creating the Pull Request

- [x] Go to "Commits" tab, make sure the commit username is clickable and linked to your GitHub account correctly.
- [x] Review the "Files changed" tab to ensure there are no unnecessary files or changes included in the pull request.
- [x] Verify that the raw.githack preview link is included in the description.
  - [x] Preview the MDwiki rendered changes using the raw.githack link. Ensure it displays as expected without any errors.
- [x] Drop a link to this pull request in our discord channel.

### Description, Screenshots and/or Screencast

Replaced the instructions about creating a pull request and deleting the branch in both step 1 ([Markdown & Forking Workflow](https://raw.githack.com/AdhamElAsfar99/AdhamElAsfar99.github.io/3326-remove-redundant-instructions/index.html#!./pages/mi/mi-github-and-markdown.md)) and step 6 ([GitHub Issues Tutorial](https://raw.githack.com/AdhamElAsfar99/AdhamElAsfar99.github.io/3326-remove-redundant-instructions/index.html#!./pages/mi/mi-github-issues.md)) by a link that leads to a new page ([Creating a Pull Request and Deleting a Branch Tutorial](https://raw.githack.com/AdhamElAsfar99/AdhamElAsfar99.github.io/3326-remove-redundant-instructions/index.html#!./pages/mi/mi-github-pull-request-and-delete-branch.md)) to eliminate redundancy in both pages.

**NOTE:** The hyperlinks provided above are the "Raw.Githack" links to each page separately. Below is the "Raw.Githack" for the main page where you can easily navigate to the other pages.

fixes #3326

### Raw.Githack Preview Link

https://raw.githack.com/AdhamElAsfar99/AdhamElAsfar99.github.io/3326-remove-redundant-instructions/index.html#!./pages/mi/mi-10-steps.md

### CODE REVIEW

**Review by xyb994 — APPROVED** [review]

**Review by dogi — APPROVED** [review]
@AdhamElAsfar99 nice one
think the only thing to make it even better is selecting a shorter new markdown file name

-> maybe `mi-github-pull-request.md`

**Comment by AdhamElAsfar99** [comment]
@dogi Thank you for the feedback!
This was the first name for the file, but I wasn't sure if it is okay not to mention the deleting branch part in the name. 
I prefer the short name too.

**Comment by AdhamElAsfar99** [comment]
@xyb994 I was checking one last time before deleting the branch and I found a bug. I forgot to update the file's name to "mi-github-pull-request.md"  in the main files referencing it, making the links invalid. What is the best way to fix this? I can create another pull request with this bug fixed, but I am not sure if this is the most efficient way to do it.

image

**Comment by xyb994** [comment]
Oops, guess I missed it too. Thank you for re-verifying and catching it quickly. Yeah, you can create an issue and another pr for it. Let us know in Discord then I'll get it merged quickly.

**Pull request merged**
