### PR TITLE
amanuely.md profile

### PR DESCRIPTION
**Pull request by amanuely**
https://rawgit.com/amanuely/amanuely.github.io/amanuel_branch/#!pages/vi/profiles/amanuely.md

### CODE REVIEW

**Comment by amanuely** [comment]
Thanks, I have fixed them

**Comment by xyb994** [comment]
@amanuely Sorry, I meant the extra space on the same line. This doesn't affect what it looks like in MDwiki or GitHub's Markdown rendering, but helps make the raw document look cleaner...

```
   # Languages   and   Technologies :
•     Java,   JavaScript   ( fluent)
•    C,   Node.js,   Linux,   AngularJS,   Python,   Git,   bootstrap,   D3.js,   Html,   CSS   (intermediate)
•    ReactJS,   SQL   ( beginner)
```

```
# Languages and Technologies
* Java, JavaScript (fluent)
* C, Node.js, Linux, AngularJS, Python, Git, bootstrap, D3.js, Html, CSS (intermediate)
* ReactJS, SQL (beginner)
```

**Comment by amanuely** [comment]
@xyb994 got you.

**Comment by xyb994** [comment]
@amanuely In general, we need at least two people's approval before merging. I suggest you get on gitter and `@all` to ask one or two more person to take a look at the PR and approve it.

**Pull request merged**
