### PR TITLE
courses manual added

### LINKED ISSUE #2360: Course Manual
**NOTE:** If it is too big to work on you can even push once part of it is complete.

Should be made on file `pages/manual/planet/course.md`
Page should contain explanation about
* Getting to Courses page
  * From **Menu**
  * From **Dashboard Tile**
* List of Courses
* Different actions on list page
  * Action Menu
  * Rating
  * Selection
  * Add to myCourse
  * Removing from myCourse
  * Filter/Search
  * Pagination
* Adding Course
   * Concept of Steps
   * Linking Resource
   * Adding Exam
   * Adding Survey
* Using collection of course
* Course View
   * Taking exam
   * Taking survey

### PR DESCRIPTION
**Pull request by sjson421**
Fixes #2360 

### Description
This is rather a big set of pages so I'd appreciate any feedback.

### Raw.Githack preview link

[Link](https://raw.githack.com/open-learning-exchange/open-learning-exchange.github.io/manual-courses/#!pages/manual/planet/course.md)

For whatever reason, if the Resources image isn't updated, use [this link](https://github.com/open-learning-exchange/open-learning-exchange.github.io/blob/manual-courses/pages/manual/planet/course.md) instead.

### CODE REVIEW

**Comment by lmmrssa** [comment]
@sjson421 Looks good but will have some more detail review as it has lot of details. Also there is link missing to reach this page
rawgit link https://raw.githack.com/open-learning-exchange/open-learning-exchange.github.io/manual-courses/#!pages/manual/planet/course.md

**Comment by sjson421** [comment]
@lmmrssa Sure thing. I'll non-assign myself the Team manual to spend more time on this one. It's a lot bigger than I thought.

**Comment by lmmrssa** [comment]
@sjson421 member.md file should not be touched
Also planet-nation-tree.png planet-nations-bubbles.png planet-dashboard.png also should not be touched.
Please make sure you just make changes related to course.
Also add link on overview to reach course page.

**Comment by sjson421** [comment]
@lmmrssa I've made no changes to the above files. I don't know why git detects them as changes but I haven't touched those.

**Pull request closed without merging**
