### PR TITLE
Uploading images #615

### PR DESCRIPTION
**Pull request by praneetharra**
I thought it is not necessary to mention how to take a screenshot, so I just added a line to clarify how to add images to chat,

### CODE REVIEW

**Comment by praneetharra** [comment]
@dogi @waryhermit should this small change work?

**Comment by dogi** [comment]
@praneetharra I love this change
but wonder also how to best add @mappuji very good suggestion ...

**Comment by praneetharra** [comment]
@mappuji @dogi are you sure we can directly paste the image in the message area? I tried it.. no success though..

**Comment by Loshma93** [comment]
@praneetharra You can simply use ctrl+c and ctrl+v to paste the image in chat. If you want to take screen shot then use alt+prt sc and ctrl+v to paste image in chat

**Comment by praneetharra** [comment]
@Loshma93 Okay. I'll update the earlier changes and add these instructions to it.

**Comment by praneetharra** [comment]
@dogi @Loshma93 @mappuji Review the update and suggest if anything else needs to be added.

**Pull request merged**
