### PR TITLE
Update team.md remove fangninghe resolves issue #719

### PR DESCRIPTION
**Pull request by Loshma93**

### CODE REVIEW

**Comment by Supriyaranjan** [comment]
@Loshma93  Do you think Should we permanently remove fangninghe or move to inactive interns?

**Comment by dogi** [comment]
@Loshma93 hmm - good question
think we should make her start be her end date ;)

**Comment by Loshma93** [comment]
@Supriyaranjan @dogi I have to move her to Inactive Interns and make her start & end date as her start date. Right??

**Comment by dogi** [comment]
@Loshma93 yes ;)

**Comment by Loshma93** [comment]
@dogi Ok

**Pull request merged**
