### PR TITLE
Add previous and next for page navigation (fixes issue #1375)

### PR DESCRIPTION
**Pull request by yaoxing1990**
https://cdn.rawgit.com/yaoxing1990/yaoxing1990.github.io/xing-fix-pagenav/#!pages/vi/vi-github-and-repositories.md

Added "previous" and "next" button in each step to navigate the user to previous step and next step

[x] Check the bottom of each step detail page to find if the "previous" and "next" link works normally

### CODE REVIEW

**Comment by kylemathias** [comment]
These buttons can not skip the introduction page. There is some important information on that page that some interns need to read. If you make the Next and Previous buttons go to the section on the first steps page corresponding to the correct page, that would be fine.

**Comment by kylemathias** [comment]
Also, those buttons could be layout so the Previous button is on the left side, and the next button is on the bottom right.

**Comment by yaoxing1990** [comment]
@kylemathias Fixed

https://rawgit.com/yaoxing1990/yaoxing1990.github.io/xing-fix-pagenav/#!./pages/vi/vi-github-and-repositories.md

Check the bottom of the page to see if "next" is in the right

**Comment by kylemathias** [comment]
the next button is alot smaller than the previous. make them the same size and aligned.

**Comment by yaoxing1990** [comment]
https://rawgit.com/yaoxing1990/yaoxing1990.github.io/xing-fix-pagenav/#!pages/vi/vi-github-and-markdown.md

@kylemathias Fixed. The rawgit link may not be updated. The code in github directory should be right 
`<div style="text-align: left"><a href="vi-first-steps.md#Step_2_-_Vagrant_Tutorial">Previous</a></div><div style="text-align: right"><a href="vi-first-steps.md#Step_4_-_BeLL-Apps_Tutorial">Next</a></div>`

**Comment by yaoxing1990** [comment]
@kylemathias The rawgit link is working now. Could you approve my pull request? Thanks.

**Comment by kylemathias** [comment]
@yaoxing1990 Your Buttons are prefect. It looks like you have made multiple changes to different files and they are all showing up on this PR. You need to separate each change into a separate PR.

**Pull request closed without merging**
