### PR TITLE
Fix './' from endlessly being added (fixes #673)

### LINKED ISSUE #673: Click on anchor # continually adds ./ in the URL
When we click on anchor `#` next to the title multiple times, it continually adds `./` in the URL. 
It should just add `./` once.

### PR DESCRIPTION
**Pull request by paulbert**
Edits the mdwiki script to fix the endless addition of './' to urls to fix #673

### CODE REVIEW

**Comment by dogi** [comment]
@paulbert can you add rawgit link so we can test this?

**Comment by paulbert** [comment]
Yes, here it is:
https://rawgit.com/paulbert/paulbert.github.io/fix_url_links/index.html#!index.md

**Comment by kylemathias** [comment]
works for me. i cant review it for i am not assigned to it.

**Comment by waryhermit** [comment]
@kylemathias You should be able to review it if you go the files changed

**Comment by dogi** [comment]
awesome - the rawgit link worked

@dogi wonders if @kylemathias did already do the offline test?

- [ ] I still need to check new change in offline local mode

**Comment by mappuji** [comment]
@dogi please wait for @paulbert for transferring his knowledge about this before merging this PR.

**Comment by paulbert** [comment]
@mappuji So this just consisted of a few small changes within the mdwiki script.  To load in each of the `.md` files into the page it uses a jQuery ajax request to pull that file.  Before they run that, they added some code to add a `./` to prevent XSS (something that I'm not very familiar with, but is a security concern).  Unfortunately, this meant that all of the links found in the markdown would then have a `./` in front of their url, so when the next page was loaded it would add another and so on.

First I made sure to stop the addition of `./` if the url already started with `./` in this commit:
https://github.com/paulbert/mdwiki/commit/ba0c90aa0eac7ab2abe5cdc602f071586bc9e18d

Then I realized in the situation that the url started with `/./` it would still add `./` indefinitely I made this commit to fix that situation:
https://github.com/paulbert/mdwiki/commit/3cd52f66dfcdbbc2c4f6c4c46a05f99caea0ace9

In the next week or so I'll try to get the mdwiki files incorporated into this repository so any changes we make are more easily seen in the pull requests.  Sorry for the lack of explanation in this one previously.

**Comment by dogi** [comment]
> In the next week or so I'll try to get the mdwiki files incorporated into this repository so any changes we make are more easily seen in the pull requests.

@paulbert awesome ;)

@mappuji @paulbert we will just create an new issue ... wonder mostly how to call it
`ole--mdwiki-vi build scripts`? or something similar ;)

Anyhow think we should also add vi-mkwiki documentation page to our projects
a page which covers stuff about
- our own mdwiki build
- link official doku
- ...

**Pull request merged**
