### PR TITLE
Completed First Steps Add to team.md

### PR DESCRIPTION
**Pull request by Loshma93**

### CODE REVIEW

**Comment by waryhermit** [comment]
Just goes to show we were not reviewing well enough haha

**Comment by Loshma93** [comment]
@dogi Do I need to make any changes to this PR in first hangout session?

**Comment by sarvanivadali** [comment]
@Loshma93 I think you will be required to meet online with @dogi and learn to 'Squash and Merge' this PR yourself.

**Comment by Loshma93** [comment]
@dogi @sarvanivadali I got it

**Pull request merged**
