### PR TITLE
fixed FAQ link

### LINKED ISSUE #1329: broken link
In http://open-learning-exchange.github.io/#!./pages/vi/vi-configurations.md there is a broken link `FAQ`
is pointing to http://open-learning-exchange.github.io/#!./pages/vi/interns/vi-faq.md#Technical_Issues_and_Questions and should point to http://open-learning-exchange.github.io/#!./pages/vi/vi-faq.md#Technical_Issues_and_Questions

### PR DESCRIPTION
**Pull request by charly3pins**
resolve #1329

### CODE REVIEW

**Comment by aas919** [comment]
@charly3pins The issue has been fixed in this pull request https://github.com/open-learning-exchange/open-learning-exchange.github.io/pull/1323. It is waiting for approval. Please consider the same.

**Comment by charly3pins** [comment]
Oh sorry @aas919 I've seen before. I think there are a lot of issues duplicated, would be good to clean up these ones. What do you think?

**Comment by kylemathias** [comment]
Im going to close this out. This was addressed in a different issue that @aas919 has mentioned.

**Comment by dogi** [comment]
@charly3pins too bad - thanks anyway ;)

**Pull request closed without merging**
