### PR TITLE
PR for fixing issue #930

### PR DESCRIPTION
**Pull request by navneetkarnam**
- This resolves issue #930 
- I feel the cheatsheet now is more simple and easy to understand
- Here is the rawgit [link](https://rawgit.com/navneetkarnam/navneetkarnam.github.io/navneetkarnam-mdpageupdate/#!pages/githubandmarkdown.md)

### CODE REVIEW

**Comment by navneetkarnam** [comment]
@aurinsomnia Yup I did search a lot of images and this is the best and the simplest I got. I believe it takes time to load when you open the page!

**Comment by navneetkarnam** [comment]
@aurinsomnia Or I can type in the whole cheat sheet and put it up instead of depending on the web images :)

**Comment by ChenjieZhou** [comment]
@aurinsomnia @navneetkarnam How about the cheatsheet in this [link](https://guides.co/g/getting-started-with-ghost/8885)

**Comment by navneetkarnam** [comment]
@aurinsomnia  How about this one? 
markdown1

**Comment by navneetkarnam** [comment]
@aurinsomnia Check the updated page using this rawgit [link](https://rawgit.com/navneetkarnam/navneetkarnam.github.io/navneetkarnam-mdpageupdate/#!pages/githubandmarkdown.md)

**Comment by navneetkarnam** [comment]
@kylemathias Can you merge this PR ? :) Thank you.

**Pull request merged**
