### PR TITLE
Placing info regarding virtualization under corresponding OS

### PR DESCRIPTION
**Pull request by prajwalajayaprakash**
* PR for resolving issue #985. I have placed the information regarding enabling virtualization under their corresponding OS.
* Here is the rawgit link:
 https://rawgit.com/prajwalajayaprakash/prajwalajayaprakash.github.io/placing-virtualization-info-correctly/#!pages/vagrant.md

### CODE REVIEW

**Comment by prajwalajayaprakash** [comment]
@sarah-lu102 Please have a look at this PR

**Comment by prajwalajayaprakash** [comment]
@sarah-lu102 I have made the requested changes.

**Comment by sarah-lu102** [comment]
Could you put a space between the paragraph and the instructions, and write "If so, here are" before the instructions sentence?

**Comment by prajwalajayaprakash** [comment]
@sarah-lu102 Hi! Please review the changes I have made.

**Pull request merged**
