### PR TITLE
Gitreposteps

### PR DESCRIPTION
**Pull request by alexkarasik**
Here is the rawgit link: 
https://rawgit.com/alexkarasik/alexkarasik.github.io/step-by-step/#!pages/gitandrepositories.md

and the Issue I was referencing was #857

### CODE REVIEW

**Comment by sarah-lu102** [comment]
looks good! can you add a rawgit link and a link to the issue in the description?

**Comment by alexkarasik** [comment]
Thanks! Is there anything else I can do or improve to get this merged?

**Comment by alexkarasik** [comment]
Here are my updates: 
https://rawgit.com/alexkarasik/alexkarasik.github.io/gitsummary/#!pages/gitandrepositories.md

**Comment by alexkarasik** [comment]
Thanks @navneetkarnam. I notice in this rawgit link that it does not say username.github.io in the first step, but i fixed that in another commit and i'm not totally sure why it hasn't been fixed.

**Comment by alexkarasik** [comment]
@aurinsomnia and @sarah-lu102 Please take a look again at my updates when you get a chance.

**Comment by alexkarasik** [comment]
@navneetkarnam and @sarah-lu102 sorry guys, but when I look at my rawgit link that I posted, I only see bullet points, so I am not entirely sure which steps you mean at the moment.

**Pull request merged**
