### PR TITLE
update faq.md 

### PR DESCRIPTION
**Pull request by yssdnj**
group all questions to the beginning of the page, and add answer link to each question.
see rawgit.com/yssdnj/yssdnj.github.io/faq_patch4_0420/#!pages/faq.md

### CODE REVIEW

**Comment by yssdnj** [comment]
link here http://www.rawgit.com/yssdnj/yssdnj.github.io/faq_patch4_0420/#!pages/faq.md 

I don't know why it shows all commits I did before. What I did in this PR is only the last one "Update faq.md"

**Comment by praneetharra** [comment]
@yssdnj I like this change. The faq page now looks little clustered and it takes time to search for something.

**Comment by kylemathias** [comment]
I didn't catch the no # next to the questions below. 
example

**Comment by yssdnj** [comment]
@waryhermit yes, that's right. It does not work in Github, but works in rawgit. I think the reason is that the github preview and [MDWiki](http://dynalon.github.io/mdwiki/#!index.md) syntax are different. In details, I guess maybe the some definations in css or html are different(not sure).

I tried to use `<a name="anchor"></a>` to anchor in the same page, but it doesn't work( [help link](http://stackoverflow.com/questions/6695439/how-to-link-to-a-named-anchor-in-multimarkdown)). Also I tried to change attribute name to id or href, still doesn't work.

So, what I did here is setting every question as head title by adding four "#". Then this head title will have a default anchor. 
For example in page faq.md you have a head title is "title four" 
`#### title four`
then when you would like to anchor that title in somewhere, you could do as below
`[link to title four](faq.md#title_four)`

I know this way is not so concise, but it is the only way I could make it work currently. 
If anyone has a better way, please feel free to comment.

**Comment by waryhermit** [comment]
@yssdnj That is a fine way. Can you make the other changes though?

**Comment by yssdnj** [comment]
@waryhermit  Hi, I have made it just now, please check it.

**Comment by yssdnj** [comment]
@kylemathias I add number to each question, please check it.

**Comment by waryhermit** [comment]
@yssdnj You should either put some kind of title between the two question types or continue the same count, I think it will confuse some people to have two `Q1`

**Comment by yssdnj** [comment]
@waryhermit  Good advice. Please check agian, and free to make any suggestions.

**Pull request merged**
