### PR TITLE
Add intern application steps to the navigation bar (Addressing Issue #938)

### PR DESCRIPTION
**Pull request by tjyothsna16**
Rawgit <a href="https://rawgit.com/tjyothsna16/tjyothsna16.github.io/add-steps-in-dropdown/#!navigation.md">here</a>.
Addressing Issue #938.

### CODE REVIEW

**Comment by kylemathias** [comment]
@tjyothsna16 I think the steps need to be a secondary pop out from "Start here"
image
Having that many main menu items show up makes it look a little cluttered.

**Comment by tjyothsna16** [comment]
I completely agree. I will have to check if the Wiki Markdown supports that feature. I don't think I was able to find it instantly. I will do some further research and comment. 
I appreciate the feedback.

**Comment by tjyothsna16** [comment]
@kylemathias I did look this up. But, I was not able to find a way to add a secondary drop down in MDWiki.  I opened an issue in MDWiki github to see if they have any response.

**Comment by kylemathias** [comment]
going to close this for now

**Pull request closed without merging**
