### PR TITLE
Create johnmdrake1.md

### PR DESCRIPTION
**Pull request by johnmdrake1**
https://raw.githack.com/johnmdrake1/johnmdrake1.github.io/add-johnmdrake1-profile/#!pages/vi/profiles/johnmdrake1.md

### CODE REVIEW

**Comment by jeevast** [comment]
@johnmdrake1 I'd recommend adding few more markdown tags.

**Comment by johnmdrake1** [comment]
On it. Thank you!

**Comment by johnmdrake1** [comment]
Changes have been made to include more markdown elements and make the page look better.

**Comment by ChiragAwale** [comment]
Looks good :D

**Pull request merged**
