### PR TITLE
Add screenshots and steps to Planet Tutorial page (fixes #2243)

### LINKED ISSUE #2243: Improve Intern Experice - Planet Tutorial Take The Course
### Problem
While taking the course from [Planet Tutorial](http://open-learning-exchange.github.io/#!./pages/vi/vi-planetapps.md), it can be confusing to figure out if the quiz answers were accepted or not. 

### Screenshots

Screenshot 1
planet tutorial course

Screenshot2
image

Screenshot 3
image

### Proposed solution

For more clarity, the tutorial could include some screenshots of what to expect when the quiz answers have been successfully submitted, as well as what the colors on the tabs mean:
1. In [Planet Tutorial](http://open-learning-exchange.github.io/#!./pages/vi/vi-planetapps.md) in section "Take the course", add a screenshot under step 4. See proposed screenshot 1 attached. 
2. Under the new screenshot, add sentence: "You can also verify that your quiz answer was submitted by clicking on "Home", then "Submissions". Add screenshot 2 under this sentence.
3. Finally add a last sentence: "You should see something like this if your quiz answers were submitted correctly:". Add screenshot 3 under this sentence.

### PR DESCRIPTION
**Pull request by diabagatekelly**
Fixes #2243

### Description
1. Added 3 new files to pages/vi/images:
*vi-planet-course.jpg
*vi-planet-submissions-button.png
*vi-planet-submissions.png
2. Added a screenshot of the completed Planet course under step 4.
3. Added a new step 5 for checking your submissions. 
4. Added 2 new screenshots under the new step 5 to show the Submissions button and the Submissions page. 
5. Changed the number of the last step from 5 to 6.

### RawGit preview link

https://raw.githack.com/diabagatekelly/diabagatekelly.github.io/issue2243/#!pages/vi/vi-planetapps.md

### CODE REVIEW

**Comment by diabagatekelly** [comment]
@lmmrssa I’ve tried different ways to add the pictures within the list but it always restarts the numbering after the images. Do you know a workaround? Or I could add all the new screenshots under the list and refer to them in the list at the appropriate place like (see image 1).

**Comment by svlesiv** [comment]
Hi @diabagatekelly,
Please take a look at a possible solution below.
```
**STEPS:** 

1. Click on `Courses` on the top navigation
2. Find the course "Virtual Interns," click on `Join`
3. Click on Course to `Open`
4. Carefully finish all steps of the course

  ![Finished Planet Course](images/vi-planet-course.jpg)

5. To verify that your course answers were submitted, click on `Home`, then on `Submissions` 

  ![Submissions button](images/vi-planet-submissions-button.png)
  ![View Submissions](images/vi-planet-submissions.png) 

6. When you provide feedback, try to be as specific as possible, and include screenshots when necessary
```

Before and after images you would need to add a blank line. Also, if you need to keep numbering of the ordered list, you would need to indent the images.

To be able to preview changes locally before creating a commit, you could test your changes using a server. http://dynalon.github.io/mdwiki/#!faq.md

**Comment by diabagatekelly** [comment]
@svlesiv thank you it seems like that worked!

**Comment by svlesiv** [comment]
@diabagatekelly Looks good:)

**Pull request merged**
