### PR TITLE
PR for updating firststeps page (issue 976) with screenshots 

### PR DESCRIPTION
**Pull request by navneetkarnam**
- This PR resolves issue #976 
- I have added the screenshots for the watch and follow steps.
- Here is the rawgit [link](https://rawgit.com/navneetkarnam/navneetkarnam.github.io/navneetkarnam-patch-3/#!pages/firststeps.md)

### CODE REVIEW

**Comment by navneetkarnam** [comment]
@aurinsomnia I agree but, these are the standard screenshots and all of the screenshots are of the same size. I'll try to make the changes and see if it works out!

**Comment by navneetkarnam** [comment]
I personally feel this image stresses on the step saying they must watch the organization repositories. I can remove the Screenshot showing the follow part. If that makes it more efficient.

**Comment by aurinsomnia** [comment]
I actually think if you just used some very basic image editor, it would be child's play for you to make a combined image, that is more effective and takes up less space. If you have a little time, or are familiar with something like GIMP or Preview, that could be much faster than trying to mess around with markdown syntax and the image formatting.

**Comment by navneetkarnam** [comment]
@aurinsomnia Sure! I guess I'll edit the image and combine the two. Thank you.

**Comment by navneetkarnam** [comment]
@aurinsomnia I tried editing the images and combining them but, the image quality goes down a lot.

**Comment by navneetkarnam** [comment]
@sarah-lu102 Done! I added spaces after the numbers too.

**Comment by navneetkarnam** [comment]
@Loshma93  Thank you :)

**Pull request merged**
