### PR TITLE
Added name to team.md (Step 9)

### PR DESCRIPTION
**Pull request by njanne19**
The title speaks for itself, but I just added my name to the bottom of the interns list in the ``interns.md`` file under ``pages``

### CODE REVIEW

**Comment by kylemathias** [comment]
@ALL please wait for @dogi and @xyb994 to merge this during the welcome interview

**Comment by alexkarasik** [comment]
@dogi met with @xyb994 and he has been added to the intern list, so I will close this now.

**Comment by dogi** [comment]
oops @njanne19 sry anyhow ping me when online ;)

**Comment by dogi** [comment]
I am closing this because of merge conflicts

@njanne19 feel free to come at us with an other PR to add yourself to the team

**Pull request closed without merging**
