### PR TITLE
2342 issue

### PR DESCRIPTION
**Pull request by smem22**
### Remove waffle.io from section [intern orientation]
[intern orientation]: http://open-learning-exchange.github.io/#!./pages/robots/rbts-intern-orientation.md

### Steps to reproduce the problem
Go to http://open-learning-exchange.github.io/#!./pages/robots/rbts-intern-orientation.md

### Screenshots of the Issue

Screen Shot 2019-06-04 at 10 32 48 AM

### Proposed solution
I just removed the waffle.io part from the markdown code.
Screen Shot 2019-06-05 at 11 26 13 AM

### Screenshots of the proposed solution
Screen Shot 2019-06-04 at 11 16 31 AM

### CODE REVIEW

**Comment by Liew211** [comment]
@smem22 please include your raw.githack link in your pull request, and follow the template.  Instructions to do so are here: http://open-learning-exchange.github.io/#!./pages/vi/vi-github-issues.md

**Comment by smem22** [comment]
Okay I'm working on it now

**Comment by Liew211** [comment]
@smem please include the raw.githack link in the body of the pull request, not the title.  See other issues for reference.

**Comment by singharpita** [comment]
@smem22 there is `Check Waffle.io, if you have no issues assigned, assign yourself to issues relating to the project you wish to work on.` line on the page please update it as well.

**Comment by ChiragAwale** [comment]
Completed in #2346

**Pull request closed without merging**
