### PR TITLE
Update navneetkarnam.md

### PR DESCRIPTION
**Pull request by navneetkarnam**
Added Few more elements to my page
1. Table showing the skills 
2. A horizontal table element with the list of languages I know

### CODE REVIEW

**Comment by navneetkarnam** [comment]
Sure I'll make the changes and let you know !

**Comment by navneetkarnam** [comment]
I did make some changes to my page. Also included the link to rawgit file in the comments section.

**Comment by snazzybunny** [comment]
@navneetkarnam Can you put the rawgit in your description in this PR. I can't seem to see any rawgit, thanks.

**Comment by navneetkarnam** [comment]
here is the link to my rawgit: https://rawgit.com/navneetkarnam/navneetkarnam.github.io/navneetkarnam-patch-1/#!pages/profiles/navneetkarnam.md

**Comment by navneetkarnam** [comment]
Thank you @aurinsomnia

**Comment by navneetkarnam** [comment]
@sarah-lu102 Thank you :)

**Pull request merged**
