### PR TITLE
Professional Coder Volunteers

### PR DESCRIPTION
**Pull request by bsocial**
This is a draft document for use with professional volunteers.

### CODE REVIEW

**Comment by kylemathias** [comment]
This FAQ page is well made, but i am not sure what it is for. Could you explain the reason behind making this page and were it is going to be implemented?

**Comment by bsocial** [comment]
Yeah good point. I should have written in up as an issue. I'll do that now and link back here.

In short, it is part of a larger effort to provide different support layers. Each one is a bit different.

Virtual Interns | Professionals | Tech Geniuses

**Comment by dogi** [comment]
https://rawgit.com/open-learning-exchange/open-learning-exchange.github.io/bsocial-3/#!pages/faq-volunteers.md

**Comment by kylemathias** [comment]
@bsocial k. Thanks for clearing it up.

**Pull request merged**
