### PR TITLE
improved step 8 in firststeps.md (#839)

### PR DESCRIPTION
**Pull request by kanishk1010**
[rawgit](https://rawgit.com/kanishk1010/kanishk1010.github.io/issue839/#!pages/firststeps.md)

- [x] Check for issue number in pull request title
- [x] Are there any unneeded files in the pull request?
- [x] Did they make a branch for their patch?
- [x] Does the pull request actually fix the issue?
- [x] Check the pull request on rawgit, does it display without any errors?
- [x] is there any merge conflicts?
- [x] Make sure that people use their GitHub accounts when making commits through git

### CODE REVIEW

**Comment by aurinsomnia** [comment]
Upon rereading I think there are a couple places where some slight grammatical changes could be made, and if you want clarification on why I can go over them with you in gitter. Obviously my changes are part personal preference, but if you or any admins feel like my phrasing makes it less understandable or worse, please do let me know.

"Create three more issues, add comments to three other issues, and resolve three issues by making the necessary changes in your repo with three separate pull requests. You will follow the same steps as in GitHub Issues, **continuing** ~~but will be working~~ to improve this Markdown Wiki so that it is **both educational** and ~~better~~ **understandable** for future ~~use~~ **interns.** ~~, much the same as in Step 6~~ ~~As you have now~~ **Just as your learning with this Wiki was made possible by the efforts of previous interns, now we turn to you to continue that tradition, and help future interns take their First Steps.** ~~thus far~~ **Through this step** you should ~~all~~ try to **further** improve ~~the clarity of the explanations for~~ **our Markdown Wiki,  through better explanations, formatting fixes, and more!** Learn by teaching - or editing our teaching tool, in this case! When you are fixing an issue, mention the number of the issue you are fixing in the description of your pull request."

I also think the last line could be added as a note, as it doesn't fit the content of the paragraph as well. As I mentioned I might have gone overboard here, but let me know what you think of my changes, and perhaps we can meet in the middle somewhere.

**Comment by kanishk1010** [comment]
@aurinsomnia I think it looks great! I was shying away from making significant changes but I love what you did here. The improvement in sentence structure and grammar makes it more appealing, yet keeping it simple and easy to understand. You have also made it more animated, which is how I would like a tutorial to be.
I also agree that the last sentence could be a note in the end. Great work!

**Comment by kanishk1010** [comment]
made the changes as above with minor tweaks.

**Comment by kanishk1010** [comment]
oops.. re-added the link. Thanks for pointing it out!

**Pull request merged**
